/**
 * Public-surface inventory for Agent Plan (F015 — Integration Test & Cross-Harness Verification).
 *
 * This module is the single, test-owned inventory of every public surface that
 * must be exercised by the scenario matrix (./scenario-matrix.mjs) and by the
 * API / MCP / Pi / UI runners built in P053–P059. It is pure data: no imports,
 * no side effects, no file reads. File:line references are kept as source anchors
 * (they may drift; the runner uses the stable `id`).
 *
 * Surfaces are grouped by harness boundary:
 *   - core : PlanStore methods + pure helper modules (@agent-plan/core)
 *   - api  : HTTP routes served by packages/plan-server/src/serve.ts
 *   - mcp  : MCP tools registered in packages/plan-mcp/src/index.ts
 *   - pi   : Pi extension commands/tools/hooks in packages/pi-adapter/src/index.ts
 *   - ui   : Web UI route loaders/actions + api client + key components
 */

/** @typedef {{
 *   id: string;
 *   kind: string;
 *   name: string;
 *   description: string;
 *   anchor: string;
 *   coverage?: {
 *     phase: string;   // P0xx phase that will exercise this surface (required when no scenario references it)
 *     reason: string;  // why the surface is deferred to that phase
 *   };
 * }} SurfaceEntry
 */

/**
 * PlanStore (class PlanStore, packages/plan-core/src/plan-store.ts) + core helpers.
 * @type {SurfaceEntry[]}
 */
export const coreSurfaces = [
  // ── Bootstrap / project ────────────────────────────────────────────
  { id: "core.init", kind: "method", name: "PlanStore.init", description: "Create a fresh .planner/ workspace (manifest, project.json, features.json, requirements.json, gitignore).", anchor: "packages/plan-core/src/plan-store.ts:853" },
  { id: "core.ensureGitignore", kind: "method", name: "PlanStore.ensureGitignore", description: "Write .planner/.gitignore transient exclusions.", anchor: "packages/plan-core/src/plan-store.ts:948", coverage: { phase: "P053", reason: "covered by core domain validation scenarios (P053)" } },
  { id: "core.exists", kind: "method", name: "PlanStore.exists", description: "True when .planner/ manifest exists.", anchor: "packages/plan-core/src/plan-store.ts:965" },
  { id: "core.loadManifest", kind: "method", name: "PlanStore.loadManifest", description: "Load manifest.json.", anchor: "packages/plan-core/src/plan-store.ts:976" },
  { id: "core.loadProject", kind: "method", name: "PlanStore.loadProject", description: "Load project.json.", anchor: "packages/plan-core/src/plan-store.ts:997" },
  { id: "core.updateProject", kind: "method", name: "PlanStore.updateProject", description: "Apply a mutator to project.json (atomic write).", anchor: "packages/plan-core/src/plan-store.ts:1764" },
  { id: "core.saveProject", kind: "method", name: "PlanStore.saveProject", description: "Persist a full project document.", anchor: "packages/plan-core/src/plan-store.ts:1788", coverage: { phase: "P053", reason: "covered by core domain validation scenarios (P053)" } },
  { id: "core.allocFeatureNumber", kind: "method", name: "PlanStore.allocFeatureNumber", description: "Allocate next global feature number.", anchor: "packages/plan-core/src/plan-store.ts:1009", coverage: { phase: "P053", reason: "covered by core domain validation scenarios (P053)" } },
  { id: "core.allocPhaseNumber", kind: "method", name: "PlanStore.allocPhaseNumber", description: "Allocate next global phase number.", anchor: "packages/plan-core/src/plan-store.ts:1010", coverage: { phase: "P053", reason: "covered by core domain validation scenarios (P053)" } },
  { id: "core.allocTaskNumber", kind: "method", name: "PlanStore.allocTaskNumber", description: "Allocate next global task number.", anchor: "packages/plan-core/src/plan-store.ts:1011", coverage: { phase: "P053", reason: "covered by core domain validation scenarios (P053)" } },

  // ── Reads ──────────────────────────────────────────────────────────
  { id: "core.loadFeatures", kind: "method", name: "PlanStore.loadFeatures", description: "Load features.json document.", anchor: "packages/plan-core/src/plan-store.ts:1096" },
  { id: "core.loadPhase", kind: "method", name: "PlanStore.loadPhase", description: "Load a single phase by id; throws when missing.", anchor: "packages/plan-core/src/plan-store.ts:1050", coverage: { phase: "P053", reason: "covered by core domain validation scenarios (P053)" } },
  { id: "core.loadAllPhases", kind: "method", name: "PlanStore.loadAllPhases", description: "Load every phase file.", anchor: "packages/plan-core/src/plan-store.ts:1262", coverage: { phase: "P053", reason: "covered by core domain validation scenarios (P053)" } },
  { id: "core.loadAll", kind: "method", name: "PlanStore.loadAll", description: "Load whole workspace (project + features + phases).", anchor: "packages/plan-core/src/plan-store.ts:1307", coverage: { phase: "P053", reason: "covered by core domain validation scenarios (P053)" } },
  { id: "core.loadWorkspace", kind: "method", name: "PlanStore.loadWorkspace", description: "Alias of loadAll.", anchor: "packages/plan-core/src/plan-store.ts:2132", coverage: { phase: "P053", reason: "covered by core domain validation scenarios (P053)" } },
  { id: "core.loadRequirements", kind: "method", name: "PlanStore.loadRequirements", description: "Load requirements.json document.", anchor: "packages/plan-core/src/plan-store.ts:1230" },
  { id: "core.phaseWorkMap", kind: "helper", name: "buildPhaseWorkMap", description: "Build a bounded priority-ordered phase map with exact sibling refs, statuses, concise goals, dependencies, and terminal-versus-remaining capability ownership so resumed agents do not duplicate planned work.", anchor: "packages/plan-core/src/task-context.ts:buildPhaseWorkMap", coverage: { phase: "P059", reason: "Covered by core task-context and handoff-context regressions plus Pi/MCP task-start and handoff surfaces." } },
  { id: "core.descriptionFreshness", kind: "helper", name: "buildHierarchicalDescriptionFreshness / PlanStore.previewDescriptionReconciliation", description: "Compute exact child-to-parent description drift and a non-mutating leaf-to-root reconciliation preview using description-specific revisions.", anchor: "packages/plan-core/src/description-freshness.ts", coverage: { phase: "P059", reason: "Covered by core, HTTP, Pi, MCP, and Web UI description-freshness regressions." } },
  { id: "core.nextWorkRecommendation", kind: "helper", name: "recommendNextWork", description: "Return a bounded priority recommendation plus typed competing claims from persisted active work, deviations, verified handoffs, and satisfied dependencies; free-form handoff Markdown and terminal archives are never authoritative action evidence.", anchor: "packages/plan-core/src/task-selection.ts:recommendNextWork", coverage: { phase: "P059", reason: "Covered by core recommendation, Pi, and MCP handoff regressions." } },
  { id: "core.reopenTask", kind: "method", name: "PlanStore.reopenTask", description: "Confirmation-gated atomic done-to-in-progress lifecycle operation that retains completion evidence and never pauses unrelated work.", anchor: "packages/plan-core/src/plan-store.ts:reopenTask", coverage: { phase: "P059", reason: "Covered by persisted core and cross-harness reopen regressions." } },
  { id: "core.ideaDiscussionSkill", kind: "method", name: "PlanStore.ideaDiscussionSkill", description: "Load the managed project-local grill-me instructions only for an Ideas discussion or promotion workflow.", anchor: "packages/plan-core/src/plan-store.ts:1299", coverage: { phase: "P060", reason: "The cross-harness verification suite covers managed project skill lifecycle; Ideas promotion callers land in P091/T358." } },
  { id: "core.linkedRequirementsForPhase", kind: "method", name: "PlanStore.linkedRequirementsForPhase", description: "Requirements whose linkedPhaseIds include the phase.", anchor: "packages/plan-core/src/plan-store.ts:1238" },
  { id: "core.loadPhaseWithRequirements", kind: "method", name: "PlanStore.loadPhaseWithRequirements", description: "Phase enriched with linkedRequirements.", anchor: "packages/plan-core/src/plan-store.ts:1243" },
  { id: "core.loadAllPhasesWithRequirements", kind: "method", name: "PlanStore.loadAllPhasesWithRequirements", description: "All phases enriched with linked requirements.", anchor: "packages/plan-core/src/plan-store.ts:1251", coverage: { phase: "P053", reason: "covered by core domain validation scenarios (P053)" } },
  { id: "core.loadPhaseDisplay", kind: "method", name: "PlanStore.loadPhaseDisplay", description: "Derived parent display (status breakdown) for a phase.", anchor: "packages/plan-core/src/plan-store.ts:1290", coverage: { phase: "P053", reason: "covered by core domain validation scenarios (P053)" } },
  { id: "core.loadFeatureDisplay", kind: "method", name: "PlanStore.loadFeatureDisplay", description: "Derived parent display for a feature.", anchor: "packages/plan-core/src/plan-store.ts:1299", coverage: { phase: "P053", reason: "covered by core domain validation scenarios (P053)" } },
  { id: "core.loadCodebaseProfile", kind: "method", name: "PlanStore.loadCodebaseProfile", description: "Load codebase profile or null.", anchor: "packages/plan-core/src/plan-store.ts:1103", coverage: { phase: "P053", reason: "covered by core domain validation scenarios (P053)" } },
  { id: "core.saveCodebaseProfile", kind: "method", name: "PlanStore.saveCodebaseProfile", description: "Persist codebase profile.", anchor: "packages/plan-core/src/plan-store.ts:1111", coverage: { phase: "P053", reason: "covered by core domain validation scenarios (P053)" } },
  { id: "core.loadActivityLog", kind: "method", name: "PlanStore.loadActivityLog", description: "Load activity log entries.", anchor: "packages/plan-core/src/plan-store.ts:1186", coverage: { phase: "P053", reason: "covered by core domain validation scenarios (P053)" } },
  { id: "core.appendActivity", kind: "method", name: "PlanStore.appendActivity", description: "Append an activity entry (type/ref/summary).", anchor: "packages/plan-core/src/plan-store.ts:1195", coverage: { phase: "P053", reason: "covered by core domain validation scenarios (P053)" } },

  // ── Writes (atomic) ────────────────────────────────────────────────
  { id: "core.saveFeature", kind: "method", name: "PlanStore.saveFeature", description: "Persist/append a feature (atomic write).", anchor: "packages/plan-core/src/plan-store.ts:1828" },
  { id: "core.updateFeatures", kind: "method", name: "PlanStore.updateFeatures", description: "Apply a mutator to features.json.", anchor: "packages/plan-core/src/plan-store.ts:1770" },
  { id: "core.saveFeatures", kind: "method", name: "PlanStore.saveFeatures", description: "Persist a full features document.", anchor: "packages/plan-core/src/plan-store.ts:1795" },
  { id: "core.updatePhase", kind: "method", name: "PlanStore.updatePhase", description: "Apply a mutator to a phase file (atomic).", anchor: "packages/plan-core/src/plan-store.ts:1873" },
  { id: "core.savePhase", kind: "method", name: "PlanStore.savePhase", description: "Persist a phase file.", anchor: "packages/plan-core/src/plan-store.ts:1873", coverage: { phase: "P053", reason: "covered by core domain validation scenarios (P053)" } },
  { id: "core.deletePhase", kind: "method", name: "PlanStore.deletePhase", description: "Delete a phase file and unlink from its feature.", anchor: "packages/plan-core/src/plan-store.ts:2120", coverage: { phase: "P053", reason: "covered by core domain validation scenarios (P053)" } },
  { id: "core.updateRequirements", kind: "method", name: "PlanStore.updateRequirements", description: "Apply a mutator to requirements.json.", anchor: "packages/plan-core/src/plan-store.ts:1782" },
  { id: "core.saveRequirements", kind: "method", name: "PlanStore.saveRequirements", description: "Persist requirements document.", anchor: "packages/plan-core/src/plan-store.ts:1839" },
  { id: "core.acceptedDecisionCreate", kind: "method", name: "PlanStore.createAcceptedDecision", description: "Create one project, feature, phase, or task Accepted Decision with planner-managed identity and acceptedAt.", anchor: "packages/plan-core/src/plan-store.ts:createAcceptedDecision", coverage: { phase: "P059", reason: "covered by cross-harness semantic Accepted Decisions regressions" } },
  { id: "core.acceptedDecisionUpdate", kind: "method", name: "PlanStore.updateAcceptedDecision", description: "Update mutable fields of one Accepted Decision while preserving identity and acceptedAt.", anchor: "packages/plan-core/src/plan-store.ts:updateAcceptedDecision", coverage: { phase: "P059", reason: "covered by cross-harness semantic Accepted Decisions regressions" } },
  { id: "core.acceptedDecisionDelete", kind: "method", name: "PlanStore.deleteAcceptedDecision", description: "Delete one explicitly identified Accepted Decision without replacing the owning array.", anchor: "packages/plan-core/src/plan-store.ts:deleteAcceptedDecision", coverage: { phase: "P059", reason: "covered by cross-harness semantic Accepted Decisions regressions" } },

  // ── Sequencing / ordering ──────────────────────────────────────────
  { id: "core.ensureStructureOrdering", kind: "method", name: "PlanStore.ensureStructureOrdering", description: "Order features/phases/tasks by number/priority.", anchor: "packages/plan-core/src/plan-store.ts:673", coverage: { phase: "P053", reason: "covered by core domain validation scenarios (P053)" } },
  { id: "core.rebuildContainment", kind: "method", name: "PlanStore.rebuildContainment", description: "Rebuild phase containment from task.phaseId.", anchor: "packages/plan-core/src/plan-store.ts:698" },
  { id: "core.ensureShortIdsAndPriority", kind: "method", name: "PlanStore.ensureShortIdsAndPriority", description: "Backfill missing shortIds + priorities (idempotent).", anchor: "packages/plan-core/src/plan-store.ts:1461", coverage: { phase: "P053", reason: "covered by core domain validation scenarios (P053)" } },
  { id: "core.nextPriority", kind: "method", name: "PlanStore.nextPriority", description: "Next display priority for a kind within parent.", anchor: "packages/plan-core/src/plan-store.ts:1439" },
  { id: "core.assignedShortIds", kind: "method", name: "PlanStore.assignedShortIds", description: "Set of shortIds already assigned.", anchor: "packages/plan-core/src/plan-store.ts:1423", coverage: { phase: "P053", reason: "covered by core domain validation scenarios (P053)" } },

  // ── Lifecycle / rollup ─────────────────────────────────────────────
  { id: "core.syncStatuses", kind: "method", name: "PlanStore.syncStatuses", description: "Derive phase+feature status from tasks; persists; returns changed refs.", anchor: "packages/plan-core/src/plan-store.ts:1685" },
  { id: "core.syncTaskStatusRollup", kind: "method", name: "PlanStore.syncTaskStatusRollup", description: "Roll one phase status up from its tasks.", anchor: "packages/plan-core/src/plan-store.ts:1696" },
  { id: "core.enableAutoSync", kind: "method", name: "PlanStore.enableAutoSync", description: "Toggle automatic status sync on writes.", anchor: "packages/plan-core/src/plan-store.ts:552", coverage: { phase: "P053", reason: "covered by core domain validation scenarios (P053)" } },
  { id: "core.runBatch", kind: "method", name: "PlanStore.runBatch", description: "Run a root-scoped cross-process write transaction with nested-write re-entrancy.", anchor: "packages/plan-core/src/plan-store.ts", coverage: { phase: "P053", reason: "covered by core domain validation and root-writer coordination scenarios" } },
  { id: "core.writeCoordination", kind: "module", name: "withPlanRootWriteLock / PlanWriterBusyError", description: "Serialize planner-root mutations across processes while leaving reads available and returning typed contention diagnostics.", anchor: "packages/plan-core/src/write-coordination.ts", coverage: { phase: "P060", reason: "covered by cross-process core and real-server integration scenarios" } },

  // ── Integrity / repair ─────────────────────────────────────────────
  { id: "core.validateIntegrity", kind: "method", name: "PlanStore.validateIntegrity", description: "Report duplicate/dangling phase ids + duplicate shortIds.", anchor: "packages/plan-core/src/plan-store.ts:1599" },
  { id: "core.repair", kind: "method", name: "PlanStore.repair", description: "Repair dangling refs, shortIds, containment; returns report.", anchor: "packages/plan-core/src/plan-store.ts:1553" },
  { id: "core.listOrphanPhases", kind: "method", name: "PlanStore.listOrphanPhases", description: "Phase files whose feature no longer resolves.", anchor: "packages/plan-core/src/plan-store.ts:2073" },
  { id: "core.cleanupOrphanPhases", kind: "method", name: "PlanStore.cleanupOrphanPhases", description: "Delete orphan phase files; returns found+removed.", anchor: "packages/plan-core/src/plan-store.ts:2096" },
  { id: "core.cleanupOrphanBackups", kind: "method", name: "PlanStore.cleanupOrphanBackups", description: "Remove stale .bak backups.", anchor: "packages/plan-core/src/plan-store.ts:1395", coverage: { phase: "P053", reason: "covered by core domain validation scenarios (P053)" } },
  { id: "core.migratePhaseIds", kind: "method", name: "PlanStore.migratePhaseIds", description: "Legacy phase-id migration (renamed/repaired/inferred).", anchor: "packages/plan-core/src/plan-store.ts:1322", coverage: { phase: "P053", reason: "covered by core domain validation scenarios (P053)" } },

  // ── Ideas Inbox ──────────────────────────────────────────────────
  { id: "core.loadIdeas", kind: "method", name: "PlanStore.loadIdeas", description: "Load rollup-independent Ideas Inbox entries.", anchor: "packages/plan-core/src/plan-store.ts", coverage: { phase: "P060", reason: "covered by cross-harness Ideas lifecycle scenarios." } },
  { id: "core.createIdea", kind: "method", name: "PlanStore.createIdea", description: "Create an Idea with monotonic I-number and short ID.", anchor: "packages/plan-core/src/plan-store.ts", coverage: { phase: "P060", reason: "covered by cross-harness Ideas lifecycle scenarios." } },
  { id: "core.updateIdea", kind: "method", name: "PlanStore.updateIdea", description: "Update Idea-owned content atomically.", anchor: "packages/plan-core/src/plan-store.ts", coverage: { phase: "P060", reason: "covered by cross-harness Ideas lifecycle scenarios." } },
  { id: "core.deleteIdea", kind: "method", name: "PlanStore.deleteIdea", description: "Delete an Idea without affecting work rollups.", anchor: "packages/plan-core/src/plan-store.ts", coverage: { phase: "P060", reason: "covered by cross-harness Ideas lifecycle scenarios." } },
  { id: "core.promoteIdea", kind: "method", name: "PlanStore.promoteIdea", description: "Record validated feature/phase/task promotion history.", anchor: "packages/plan-core/src/plan-store.ts", coverage: { phase: "P060", reason: "covered by cross-harness Ideas lifecycle scenarios." } },

  // ── Handoff (entity-scoped) ────────────────────────────────────────
  { id: "core.getPhaseHandoff", kind: "method", name: "PlanStore.getPhaseHandoff", description: "Read phase.handoff content.", anchor: "packages/plan-core/src/plan-store.ts:1901" },
  { id: "core.setPhaseHandoff", kind: "method", name: "PlanStore.setPhaseHandoff", description: "Write phase.handoff + handoffUpdatedAt.", anchor: "packages/plan-core/src/plan-store.ts:1908" },
  { id: "core.clearPhaseHandoff", kind: "method", name: "PlanStore.clearPhaseHandoff", description: "Clear phase.handoff, archive copy to .local/handoff-archive/, keep audit timestamps.", anchor: "packages/plan-core/src/plan-store.ts:1969" },
  { id: "core.markHandoffRead", kind: "method", name: "PlanStore.markHandoffRead", description: "Set phase.handoffReadAt.", anchor: "packages/plan-core/src/plan-store.ts:1925", coverage: { phase: "P053", reason: "covered by core domain validation scenarios (P053)" } },
  { id: "core.listHandoffs", kind: "method", name: "PlanStore.listHandoffs", description: "Phases with non-empty handoff (composite ref, first line, updatedAt).", anchor: "packages/plan-core/src/plan-store.ts:2016" },
  { id: "core.listArchivedHandoffs", kind: "method", name: "PlanStore.listArchivedHandoffs", description: "Archived handoffs for canonical terminal phase outcomes, replacement, or manual clear.", anchor: "packages/plan-core/src/plan-store.ts:2044" },
  { id: "core.cleanupStaleHandoffs", kind: "method", name: "PlanStore.cleanupStaleHandoffs", description: "Auto-archive handoffs for every canonical terminal phase outcome.", anchor: "packages/plan-core/src/plan-store.ts:2008" },
  { id: "core.preparePhaseHandoff", kind: "method", name: "PlanStore.preparePhaseHandoff", description: "Return the exact pre-draft scaffold, structured required human inputs, planner-generated metadata contract, source-review/cold-start inventory, current token, and missing durable task evidence.", anchor: "packages/plan-core/src/plan-store.ts:preparePhaseHandoff", coverage: { phase: "P060", reason: "covered by handoff context and cross-harness regression scenarios" } },
  { id: "core.refreshPhaseHandoff", kind: "method", name: "PlanStore.refreshPhaseHandoff", description: "Atomically persist a compact resume capsule; oversized bodies auto-externalize to planner-owned Markdown with symlink/traversal rejection.", anchor: "packages/plan-core/src/plan-store.ts:refreshPhaseHandoff", coverage: { phase: "P059", reason: "Covered by core externalization, cold-resume, and symlink regressions." } },
  { id: "core.handoffExternalization", kind: "helper", name: "externalizeOversizedHandoffContent", description: "Compact oversized handoffs to the 8,000-character resume capsule and retain the full body in one planner-owned document.", anchor: "packages/plan-core/src/handoff-context.ts:externalizeOversizedHandoffContent", coverage: { phase: "P059", reason: "Covered by core externalization and cold-resume regressions." } },
  { id: "core.importLegacyHandoffFile", kind: "method", name: "PlanStore.importLegacyHandoffFile", description: "One-time import of deprecated .planner/HANDOFF.md.", anchor: "packages/plan-core/src/plan-store.ts:1936", coverage: { phase: "P053", reason: "covered by core domain validation scenarios (P053)" } },

  // ── Resume / guard ─────────────────────────────────────────────────
  { id: "core.loadResume", kind: "method", name: "PlanStore.loadResume", description: "Load resume focus or null.", anchor: "packages/plan-core/src/plan-store.ts:1117" },
  { id: "core.saveResume", kind: "method", name: "PlanStore.saveResume", description: "Persist resume focus.", anchor: "packages/plan-core/src/plan-store.ts:1126" },
  { id: "core.refreshResume", kind: "method", name: "PlanStore.refreshResume", description: "Rebuild resume focus from current state (notes + summary).", anchor: "packages/plan-core/src/plan-store.ts:1209" },
  { id: "core.authorizeGuardBypass", kind: "method", name: "PlanStore.authorizeGuardBypass", description: "Persist a guard bypass window.", anchor: "packages/plan-core/src/plan-store.ts:1149", coverage: { phase: "P056", reason: "covered by Pi adapter guard-bypass lifecycle scenarios (P056)" } },
  { id: "core.clearGuardBypass", kind: "method", name: "PlanStore.clearGuardBypass", description: "Revoke guard bypass.", anchor: "packages/plan-core/src/plan-store.ts:1169", coverage: { phase: "P056", reason: "covered by Pi adapter guard-bypass lifecycle scenarios (P056)" } },
  { id: "core.isGuardBypassed", kind: "method", name: "PlanStore.isGuardBypassed", description: "Whether a bypass window is active.", anchor: "packages/plan-core/src/plan-store.ts:1178", coverage: { phase: "P056", reason: "covered by Pi adapter guard-bypass lifecycle scenarios (P056)" } },

  // ── Generated views / exports ──────────────────────────────────────
  { id: "core.writeGenerated", kind: "method", name: "PlanStore.writeGenerated", description: "Regenerate markdown views under .planner/.local/generated/.", anchor: "packages/plan-core/src/plan-store.ts:2145", coverage: { phase: "P053", reason: "covered by core domain validation scenarios (P053)" } },
  { id: "core.renderer", kind: "module", name: "PlanRenderer", description: "Markdown rendering of the plan (renderer.ts).", anchor: "packages/plan-core/src/renderer.ts:20", coverage: { phase: "P053", reason: "covered by core domain validation scenarios (P053)" } },
  { id: "core.exportService", kind: "module", name: "ExportService", description: "Markdown export of the whole plan (export-service.ts).", anchor: "packages/plan-core/src/export-service.ts:32", coverage: { phase: "P054", reason: "covered via the API export endpoint scenarios (P054)" } },
  { id: "core.buildRecap", kind: "function", name: "buildRecap", description: "Harness-agnostic recap text (pi | mcp).", anchor: "packages/plan-core/src/recap.ts:39" },
  { id: "core.buildPhaseContextBlock", kind: "function", name: "buildPhaseContextBlock", description: "Task-start context including project/feature/phase/task Accepted Decisions and linked Requirements.", anchor: "packages/plan-core/src/task-context.ts:buildPhaseContextBlock", coverage: { phase: "P059", reason: "covered by cross-harness task-start canonical context regressions." } },
  { id: "core.boundedAcceptedDecisionContext", kind: "function", name: "buildBoundedAcceptedDecisionContext", description: "Bound ambient/load Accepted Decision context while preserving explicit truncation guidance.", anchor: "packages/plan-core/src/task-context.ts:buildBoundedAcceptedDecisionContext", coverage: { phase: "P059", reason: "covered by core bounded-context and MCP/Pi load-context regressions." } },
  { id: "core.markCanonicalFullRead", kind: "function", name: "markCanonicalFullReadForSessionId", description: "Refuse feature/phase/task read attestation when any canonical Accepted Decision field is omitted.", anchor: "packages/plan-core/src/read-tracking.ts:markCanonicalFullReadForSessionId", coverage: { phase: "P059", reason: "covered by core omission rejection and cross-harness full-read regressions." } },
  { id: "core.packageVersion", kind: "module", name: "package-version.ts", description: "Resolve package versions from the manifests of modules actually loaded by a harness.", anchor: "packages/plan-core/src/package-version.ts", coverage: { phase: "P059", reason: "Runtime version normalization is covered by the cross-harness contract matrix (P059)." } },
  { id: "core.runtimeDiagnostics", kind: "module", name: "runtime-diagnostics.ts", description: "Expose loaded-runtime provenance helpers, plan schema version, allocation registry version, supported allocation kinds, and typed compatibility upgrade diagnostics.", anchor: "packages/plan-core/src/runtime-diagnostics.ts", coverage: { phase: "P059", reason: "covered by runtime diagnostics and false-success mutation response regressions." } },
  { id: "core.requirementReadEligibility", kind: "function", name: "requirementReadEligibilityForSession", description: "Report exact missing/stale target-linked Requirement reads while reusing only fresh delivered session evidence.", anchor: "packages/plan-core/src/read-tracking.ts:requirementReadEligibilityForSession", coverage: { phase: "P059", reason: "covered by core and cross-harness target-scoped Requirement read regressions." } },

  // ── Pure helpers ───────────────────────────────────────────────────
  { id: "core.naming", kind: "module", name: "naming.ts", description: "createFeatureId/PhaseId/TaskId/RequirementId, shortIds, slugs, ref formatters, isUuid, validateResolvedTarget.", anchor: "packages/plan-core/src/naming.ts" },
  { id: "core.refs", kind: "module", name: "refs.ts", description: "findPhaseByRef / findTaskByRef (composite P00x, shortId, UUID, title).", anchor: "packages/plan-core/src/refs.ts" },
  { id: "core.checklist", kind: "module", name: "checklist.ts", description: "find/add/remove/toggle checklist items with C{n} selectors.", anchor: "packages/plan-core/src/checklist.ts" },
  { id: "core.displayStatus", kind: "module", name: "display-status.ts", description: "countBreakdown / deriveParentDisplay / toWorkflowStatus / fromCanonicalStatus.", anchor: "packages/plan-core/src/display-status.ts" },
  { id: "core.schema", kind: "module", name: "schema.ts", description: "Zod schemas for Feature/Phase/Task/Project/Manifest + needsMotivation.", anchor: "packages/plan-core/src/schema.ts:149", coverage: { phase: "P053", reason: "covered by core domain validation scenarios (P053)" } },
  { id: "core.needsMotivation", kind: "function", name: "needsMotivation", description: "True when a status transition requires a motivation note.", anchor: "packages/plan-core/src/schema.ts:149" },
];

/**
 * HTTP API routes (packages/plan-server/src/serve.ts — createApiApp).
 * @type {SurfaceEntry[]}
 */
export const apiSurfaces = [
  { id: "api.health", kind: "route", name: "GET /api/health", description: "Server liveness + plan root.", anchor: "packages/plan-server/src/serve.ts:914" },
  { id: "api.uiConfig", kind: "route", name: "GET /api/ui-config", description: "UI runtime config (shortcuts, server urls).", anchor: "packages/plan-server/src/serve.ts:915", coverage: { phase: "P054", reason: "covered by HTTP server integration scenarios (P054)" } },
  { id: "api.internalNotify", kind: "route", name: "POST /api/internal/notify", description: "Cross-process live-update ping.", anchor: "packages/plan-server/src/serve.ts:170", coverage: { phase: "P054", reason: "covered by HTTP server integration scenarios (P054)" } },
  { id: "api.export", kind: "route", name: "GET /api/export?full=", description: "Markdown export (writes EXPORT.md).", anchor: "packages/plan-server/src/serve.ts:190", coverage: { phase: "P054", reason: "covered by HTTP server integration scenarios (P054)" } },
  { id: "api.getProject", kind: "route", name: "GET /api/project", description: "Project document + planRoot/projectRoot.", anchor: "packages/plan-server/src/serve.ts:202" },
  { id: "api.updateProject", kind: "route", name: "PUT /api/project", description: "Replace project document.", anchor: "packages/plan-server/src/serve.ts:211" },
  { id: "api.acceptedDecisionCreate", kind: "route", name: "POST /api/accepted-decisions", description: "Create one Accepted Decision for a project, feature, phase, or task owner.", anchor: "packages/plan-server/src/serve.ts:/accepted-decisions", coverage: { phase: "P059", reason: "covered by cross-harness semantic Accepted Decisions regressions" } },
  { id: "api.acceptedDecisionUpdate", kind: "route", name: "PUT /api/accepted-decisions/:decisionId", description: "Update one Accepted Decision and preserve planner-owned metadata.", anchor: "packages/plan-server/src/serve.ts:/accepted-decisions/:decisionId", coverage: { phase: "P059", reason: "covered by cross-harness semantic Accepted Decisions regressions" } },
  { id: "api.acceptedDecisionDelete", kind: "route", name: "DELETE /api/accepted-decisions/:decisionId", description: "Delete one Accepted Decision after explicit confirmation.", anchor: "packages/plan-server/src/serve.ts:/accepted-decisions/:decisionId", coverage: { phase: "P059", reason: "covered by cross-harness semantic Accepted Decisions regressions" } },
  { id: "api.getRequirements", kind: "route", name: "GET /api/requirements", description: "Statusless declarative product Requirements document.", anchor: "packages/plan-server/src/serve.ts:221", coverage: { phase: "P054", reason: "covered by HTTP server integration scenarios (P054)" } },
  { id: "api.createRequirement", kind: "route", name: "POST /api/requirements", description: "Create a statusless product Requirement; reject legacy top-level status (201/400).", anchor: "packages/plan-server/src/serve.ts:223" },
  { id: "api.updateRequirement", kind: "route", name: "PUT /api/requirements/:id", description: "Update product outcome/linkage/macro tasks; reject top-level status; 404 when missing.", anchor: "packages/plan-server/src/serve.ts:232" },
  { id: "api.deleteRequirement", kind: "route", name: "DELETE /api/requirements/:id", description: "Delete requirement; 404 when missing.", anchor: "packages/plan-server/src/serve.ts:250", coverage: { phase: "P054", reason: "covered by HTTP server integration scenarios (P054)" } },
  { id: "api.getIdeas", kind: "route", name: "GET /api/ideas", description: "List independent Ideas Inbox entries.", anchor: "packages/plan-server/src/serve.ts", coverage: { phase: "P054", reason: "covered by real HTTP Ideas CRUD scenarios." } },
  { id: "api.createIdea", kind: "route", name: "POST /api/ideas", description: "Create an Idea with server-owned identity.", anchor: "packages/plan-server/src/serve.ts", coverage: { phase: "P054", reason: "covered by real HTTP Ideas CRUD scenarios." } },
  { id: "api.updateIdea", kind: "route", name: "PUT /api/ideas/:id", description: "Update Idea-owned title and description.", anchor: "packages/plan-server/src/serve.ts", coverage: { phase: "P054", reason: "covered by real HTTP Ideas CRUD scenarios." } },
  { id: "api.deleteIdea", kind: "route", name: "DELETE /api/ideas/:id", description: "Delete an Idea without affecting work rollups.", anchor: "packages/plan-server/src/serve.ts", coverage: { phase: "P054", reason: "covered by real HTTP Ideas CRUD scenarios." } },
  { id: "api.descriptionFreshness", kind: "route", name: "GET /api/description-freshness", description: "Return exact stale parent refs and a non-mutating leaf-to-root reconciliation preview.", anchor: "packages/plan-server/src/serve.ts:/description-freshness", coverage: { phase: "P059", reason: "Covered by real HTTP description-freshness reconciliation regression." } },
  { id: "api.getFeatures", kind: "route", name: "GET /api/features", description: "All features.", anchor: "packages/plan-server/src/serve.ts:266" },
  { id: "api.createFeature", kind: "route", name: "POST /api/features", description: "Create feature; 400 when name missing.", anchor: "packages/plan-server/src/serve.ts:268" },
  { id: "api.getFeature", kind: "route", name: "GET /api/features/:id", description: "Single feature; 404 when missing.", anchor: "packages/plan-server/src/serve.ts:310" },
  { id: "api.updateFeature", kind: "route", name: "PUT /api/features/:id", description: "Update canonical feature fields; rejects derived-status changes and raw Accepted Decisions replacement.", anchor: "packages/plan-server/src/serve.ts:318", coverage: { phase: "P059", reason: "covered by cross-harness mutation parity regressions" } },
  { id: "api.deleteFeature", kind: "route", name: "DELETE /api/features/:id", description: "Delete feature.", anchor: "packages/plan-server/src/serve.ts:343", coverage: { phase: "P054", reason: "covered by HTTP server integration scenarios (P054)" } },
  { id: "api.getPhases", kind: "route", name: "GET /api/phases?featureId=", description: "All phases (optionally filtered by feature) with linked requirements.", anchor: "packages/plan-server/src/serve.ts:357" },
  { id: "api.createPhase", kind: "route", name: "POST /api/phases", description: "Create phase; 400 missing title/featureId.", anchor: "packages/plan-server/src/serve.ts:364" },
  { id: "api.getPhase", kind: "route", name: "GET /api/phases/:id", description: "Phase with linked requirements; 404 when missing.", anchor: "packages/plan-server/src/serve.ts:452" },
  { id: "api.updatePhase", kind: "route", name: "PUT /api/phases/:id", description: "Update canonical phase planning fields and parent relinking; rejects derived-status changes and raw Accepted Decisions replacement.", anchor: "packages/plan-server/src/serve.ts:462", coverage: { phase: "P059", reason: "covered by cross-harness mutation parity regressions" } },
  { id: "api.deletePhase", kind: "route", name: "DELETE /api/phases/:id", description: "Delete phase + unlink from feature.", anchor: "packages/plan-server/src/serve.ts:484", coverage: { phase: "P054", reason: "covered by HTTP server integration scenarios (P054)" } },
  { id: "api.createTask", kind: "route", name: "POST /api/phases/:phaseId/tasks", description: "Create task; 400 missing title/phase.", anchor: "packages/plan-server/src/serve.ts:505" },
  { id: "api.getActiveTasks", kind: "route", name: "GET /api/tasks/active", description: "In-progress tasks with composite numbers.", anchor: "packages/plan-server/src/serve.ts:574", coverage: { phase: "P054", reason: "covered by HTTP server integration scenarios (P054)" } },
  { id: "api.getTaskFocus", kind: "route", name: "GET /api/tasks/focus", description: "Active, pending-resume, and next-work task summaries with pending-resume checkpoints.", anchor: "packages/plan-server/src/serve.ts:640", coverage: { phase: "P059", reason: "Suspension focus feed (F005/P066); registered in F015 cross-harness inventory, scenario deferred to P059." } },
  { id: "api.getTask", kind: "route", name: "GET /api/tasks/:id", description: "Single task; 404 when missing.", anchor: "packages/plan-server/src/serve.ts:607" },
  { id: "api.updateTask", kind: "route", name: "PUT /api/tasks/:id", description: "Update canonical task context fields with lifecycle/motivation gates; rejects raw Accepted Decisions replacement.", anchor: "packages/plan-server/src/serve.ts:617", coverage: { phase: "P059", reason: "covered by cross-harness mutation parity regressions" } },
  { id: "api.reopenTask", kind: "route", name: "POST /api/tasks/:id/reopen", description: "Confirmation-gated semantic reopen endpoint with persisted read-back and typed failures.", anchor: "packages/plan-server/src/serve.ts:tasks/:id/reopen", coverage: { phase: "P059", reason: "Covered by server reopen regressions." } },
  { id: "api.deleteTask", kind: "route", name: "DELETE /api/tasks/:id", description: "Delete task.", anchor: "packages/plan-server/src/serve.ts:701", coverage: { phase: "P054", reason: "covered by HTTP server integration scenarios (P054)" } },
  { id: "api.integrity", kind: "route", name: "GET /api/integrity", description: "Integrity report.", anchor: "packages/plan-server/src/serve.ts:723" },
  { id: "api.repair", kind: "route", name: "POST /api/repair", description: "Run repair.", anchor: "packages/plan-server/src/serve.ts:728" },
  { id: "api.reorder", kind: "route", name: "POST /api/reorder", description: "Reorder feature/phase/task by priority midpoint insert.", anchor: "packages/plan-server/src/serve.ts:737" },
  { id: "api.render", kind: "route", name: "POST /api/render", description: "Regenerate generated views.", anchor: "packages/plan-server/src/serve.ts:853", coverage: { phase: "P054", reason: "covered by HTTP server integration scenarios (P054)" } },
  { id: "api.listHandoffs", kind: "route", name: "GET /api/handoffs", description: "Pending entity-scoped handoffs.", anchor: "packages/plan-server/src/serve.ts:860" },
  { id: "api.listHandoffsArchive", kind: "route", name: "GET /api/handoffs/archive", description: "Archived handoffs.", anchor: "packages/plan-server/src/serve.ts:865" },
  { id: "api.getPhaseHandoffPreflight", kind: "route", name: "GET /api/phases/:id/handoff/preflight", description: "Return structured required handoff inputs and planner-generated metadata before drafting.", anchor: "packages/plan-server/src/serve.ts:handoff-preflight", coverage: { phase: "P059", reason: "Covered by real HTTP handoff preflight regression." } },
  { id: "api.getPhaseHandoff", kind: "route", name: "GET /api/phases/:id/handoff", description: "Phase handoff content + updatedAt.", anchor: "packages/plan-server/src/serve.ts:870", coverage: { phase: "P054", reason: "covered by HTTP server integration scenarios (P054)" } },
  { id: "api.setPhaseHandoff", kind: "route", name: "PUT /api/phases/:id/handoff", description: "Write handoff; empty content clears.", anchor: "packages/plan-server/src/serve.ts:879" },
  { id: "api.clearPhaseHandoff", kind: "route", name: "DELETE /api/phases/:id/handoff", description: "Clear handoff (archives).", anchor: "packages/plan-server/src/serve.ts:901" },
  { id: "api.docsView", kind: "route", name: "GET /api/docs/view", description: "Path-safe planner Markdown viewer (traversal/symlink rejected).", anchor: "packages/plan-server/src/serve.ts:/docs/view", coverage: { phase: "P059", reason: "Covered by server docs traversal/confirmed-save regression." } },
  { id: "api.docsSave", kind: "route", name: "PUT /api/docs/save", description: "Confirmed planner Markdown save in .planner/docs (explicit confirmed=true).", anchor: "packages/plan-server/src/serve.ts:/docs/save", coverage: { phase: "P059", reason: "Covered by server docs traversal/confirmed-save regression." } },
  { id: "api.busy", kind: "route", name: "GET/other when isBusy", description: "503 on reads / 409 on mutations while plan busy.", anchor: "packages/plan-server/src/serve.ts:156", coverage: { phase: "P054", reason: "covered by HTTP server integration scenarios (P054)" } },
  { id: "api.spa", kind: "route", name: "GET /* static", description: "SPA static serving with index.html fallback.", anchor: "packages/plan-server/src/serve.ts:962" },
  { id: "api.ws", kind: "route", name: "WS /ws", description: "WebSocket hub: connected/ping-pong/file-changed/plan-rendered events.", anchor: "packages/plan-server/src/ws-hub.ts:24", coverage: { phase: "P054", reason: "covered by HTTP server integration scenarios (P054)" } },
];

/**
 * MCP tools (packages/plan-mcp/src/index.ts).
 * @type {SurfaceEntry[]}
 */
export const mcpSurfaces = [
  { id: "mcp.version", kind: "tool", name: "planner-version", description: "Report the loaded MCP and core package versions without requiring a planner workspace.", anchor: "packages/plan-mcp/src/index.ts:164", coverage: { phase: "P059", reason: "Version parity across Claude and Codex uses the cross-harness contract matrix (P059)." } },
  { id: "mcp.init", kind: "tool", name: "planner-init", description: "Initialize .planner/ in AGENT_PLAN_ROOT or cwd.", anchor: "packages/plan-mcp/src/index.ts:205" },
  { id: "mcp.show", kind: "tool", name: "planner-show", description: "Overview recap of the plan.", anchor: "packages/plan-mcp/src/index.ts:223", coverage: { phase: "P055", reason: "covered by MCP adapter scenarios (P055)" } },
  { id: "mcp.descriptionFreshness", kind: "tool", name: "planner-description-freshness", description: "Preview exact stale feature/phase refs and explicit reconciliation steps without rewriting parent prose.", anchor: "packages/plan-mcp/src/index.ts:planner-description-freshness", coverage: { phase: "P059", reason: "Covered by MCP hierarchical freshness regression." } },
  { id: "mcp.repair", kind: "tool", name: "planner-repair", description: "Repair plan integrity.", anchor: "packages/plan-mcp/src/index.ts:263", coverage: { phase: "P055", reason: "covered by MCP adapter scenarios (P055)" } },
  { id: "mcp.cleanupOrphanPhases", kind: "tool", name: "planner-cleanup-orphan-phases", description: "List/delete orphan phase files.", anchor: "packages/plan-mcp/src/index.ts:271" },
  { id: "mcp.export", kind: "tool", name: "planner-export", description: "Markdown export.", anchor: "packages/plan-mcp/src/index.ts:168", coverage: { phase: "P055", reason: "covered by MCP adapter scenarios (P055)" } },
  { id: "mcp.authorizeBypass", kind: "tool", name: "planner-authorize-bypass", description: "Guard bypass window.", anchor: "packages/plan-mcp/src/index.ts:185", coverage: { phase: "P055", reason: "covered by MCP adapter scenarios (P055)" } },
  { id: "mcp.clearBypass", kind: "tool", name: "planner-clear-bypass", description: "Revoke guard bypass.", anchor: "packages/plan-mcp/src/index.ts:197", coverage: { phase: "P055", reason: "covered by MCP adapter scenarios (P055)" } },
  { id: "mcp.projectLanguage", kind: "tool", name: "planner-project-language", description: "Persist language preferences.", anchor: "packages/plan-mcp/src/index.ts:297", coverage: { phase: "P055", reason: "covered by MCP adapter scenarios (P055)" } },
  { id: "mcp.projectDiscuss", kind: "tool", name: "planner-project-discuss", description: "Project discovery.", anchor: "packages/plan-mcp/src/index.ts:312", coverage: { phase: "P055", reason: "covered by MCP adapter scenarios (P055)" } },
  { id: "mcp.projectGuidelinesShow", kind: "tool", name: "planner-project-guidelines-show", description: "Read canonical Project Guidelines.", anchor: "packages/plan-mcp/src/index.ts:467", coverage: { phase: "P055", reason: "covered by MCP adapter integration scenarios in the published tool suite." } },
  { id: "mcp.projectGuidelinesUpdate", kind: "tool", name: "planner-project-guidelines-update", description: "Replace canonical Project Guidelines.", anchor: "packages/plan-mcp/src/index.ts:486", coverage: { phase: "P055", reason: "covered by MCP adapter integration scenarios in the published tool suite." } },
  { id: "mcp.projectContextMigrate", kind: "tool", name: "planner-project-context-migrate", description: "Preview or apply explicit legacy project-context migration.", anchor: "packages/plan-mcp/src/index.ts:544", coverage: { phase: "P055", reason: "covered by MCP adapter integration scenarios in the published tool suite." } },
  { id: "mcp.acceptedDecisionCreate", kind: "tool", name: "planner-accepted-decision-create", description: "Create one Accepted Decision on any canonical owner.", anchor: "packages/plan-mcp/src/index.ts:planner-accepted-decision-create", coverage: { phase: "P059", reason: "covered by MCP semantic Accepted Decisions CRUD regressions" } },
  { id: "mcp.acceptedDecisionUpdate", kind: "tool", name: "planner-accepted-decision-update", description: "Update one Accepted Decision while preserving planner-owned metadata.", anchor: "packages/plan-mcp/src/index.ts:planner-accepted-decision-update", coverage: { phase: "P059", reason: "covered by MCP semantic Accepted Decisions CRUD regressions" } },
  { id: "mcp.acceptedDecisionDelete", kind: "tool", name: "planner-accepted-decision-delete", description: "Delete one Accepted Decision after explicit confirmation.", anchor: "packages/plan-mcp/src/index.ts:planner-accepted-decision-delete", coverage: { phase: "P059", reason: "covered by MCP semantic Accepted Decisions CRUD regressions" } },
  { id: "mcp.requirementList", kind: "tool", name: "planner-requirement-list", description: "List statusless product Requirements without attestation, or deliver and attest only target-relevant Requirements when phaseRef is supplied.", anchor: "packages/plan-mcp/src/index.ts:planner-requirement-list", coverage: { phase: "P059", reason: "covered by cross-harness target-scoped requirement-read regressions." } },
  { id: "mcp.requirementCreate", kind: "tool", name: "planner-requirement-create", description: "Create statusless product Requirements with planner-managed macro-task metadata; route coding/process rules to Project Guidelines.", anchor: "packages/plan-mcp/src/index.ts:2056", coverage: { phase: "P055", reason: "covered by MCP requirement parity integration scenarios." } },
  { id: "mcp.requirementUpdate", kind: "tool", name: "planner-requirement-update", description: "Update statusless Requirement outcomes, linkage, and ordered macro tasks; route coding/process rules to Project Guidelines.", anchor: "packages/plan-mcp/src/index.ts:2097", coverage: { phase: "P055", reason: "covered by MCP requirement parity integration scenarios." } },
  { id: "mcp.requirementDelete", kind: "tool", name: "planner-requirement-delete", description: "Delete a requirement after confirmation.", anchor: "packages/plan-mcp/src/index.ts:2155", coverage: { phase: "P055", reason: "covered by MCP requirement parity integration scenarios." } },
  { id: "mcp.ideaList", kind: "tool", name: "planner-idea-list", description: "List Ideas Inbox entries.", anchor: "packages/plan-mcp/src/index.ts", coverage: { phase: "P055", reason: "covered by real MCP Ideas transport scenarios." } },
  { id: "mcp.ideaShow", kind: "tool", name: "planner-idea-show", description: "Show one Idea.", anchor: "packages/plan-mcp/src/index.ts", coverage: { phase: "P055", reason: "covered by real MCP Ideas transport scenarios." } },
  { id: "mcp.ideaCreate", kind: "tool", name: "planner-idea-create", description: "Create an Idea.", anchor: "packages/plan-mcp/src/index.ts", coverage: { phase: "P055", reason: "covered by real MCP Ideas transport scenarios." } },
  { id: "mcp.ideaUpdate", kind: "tool", name: "planner-idea-update", description: "Update an Idea.", anchor: "packages/plan-mcp/src/index.ts", coverage: { phase: "P055", reason: "covered by real MCP Ideas transport scenarios." } },
  { id: "mcp.ideaDelete", kind: "tool", name: "planner-idea-delete", description: "Delete a confirmed Idea.", anchor: "packages/plan-mcp/src/index.ts", coverage: { phase: "P055", reason: "covered by real MCP Ideas transport scenarios." } },
  { id: "mcp.ideaPromotionBegin", kind: "tool", name: "planner-idea-promotion-begin", description: "Load grill-me and propose a promotion without writes.", anchor: "packages/plan-mcp/src/index.ts", coverage: { phase: "P055", reason: "covered by real MCP Ideas transport scenarios." } },
  { id: "mcp.ideaPromotionFinalize", kind: "tool", name: "planner-idea-promotion-finalize", description: "Record a confirmed promotion to a validated target.", anchor: "packages/plan-mcp/src/index.ts", coverage: { phase: "P055", reason: "covered by real MCP Ideas transport scenarios." } },
  { id: "mcp.featureList", kind: "tool", name: "planner-feature-list", description: "Compact feature list.", anchor: "packages/plan-mcp/src/index.ts:337", coverage: { phase: "P055", reason: "covered by MCP adapter scenarios (P055)" } },
  { id: "mcp.phaseList", kind: "tool", name: "planner-phase-list", description: "Compact phase list.", anchor: "packages/plan-mcp/src/index.ts:353", coverage: { phase: "P055", reason: "covered by MCP adapter scenarios (P055)" } },
  { id: "mcp.taskList", kind: "tool", name: "planner-task-list", description: "Compact task list.", anchor: "packages/plan-mcp/src/index.ts:374", coverage: { phase: "P055", reason: "covered by MCP adapter scenarios (P055)" } },
  { id: "mcp.featureAdd", kind: "tool", name: "planner-feature-add", description: "Create feature (validates name).", anchor: "packages/plan-mcp/src/index.ts:401" },
  { id: "mcp.featureShow", kind: "tool", name: "planner-feature-show", description: "Feature detail with canonical Accepted Decisions before full-read attestation.", anchor: "packages/plan-mcp/src/index.ts:planner-feature-show", coverage: { phase: "P059", reason: "covered by MCP Accepted Decision full-read regressions." } },
  { id: "mcp.featureDiscuss", kind: "tool", name: "planner-feature-discuss", description: "Persist feature discovery.", anchor: "packages/plan-mcp/src/index.ts:458", coverage: { phase: "P055", reason: "covered by MCP adapter scenarios (P055)" } },
  { id: "mcp.featureUpdate", kind: "tool", name: "planner-feature-update", description: "Update canonical feature context fields while keeping derived status read-only.", anchor: "packages/plan-mcp/src/index.ts:490", coverage: { phase: "P059", reason: "covered by cross-harness mutation parity regressions" } },
  { id: "mcp.featureDelete", kind: "tool", name: "planner-feature-delete", description: "Delete feature.", anchor: "packages/plan-mcp/src/index.ts:527", coverage: { phase: "P055", reason: "covered by MCP adapter scenarios (P055)" } },
  { id: "mcp.phaseAdd", kind: "tool", name: "planner-phase-add", description: "Create phase under a feature.", anchor: "packages/plan-mcp/src/index.ts:556" },
  { id: "mcp.phaseShow", kind: "tool", name: "planner-phase-show", description: "Phase detail with canonical Accepted Decisions and linked Requirements before full-read attestation.", anchor: "packages/plan-mcp/src/index.ts:planner-phase-show", coverage: { phase: "P059", reason: "covered by MCP Accepted Decision full-read regressions." } },
  { id: "mcp.phaseDiscuss", kind: "tool", name: "planner-phase-discuss", description: "Persist phase discovery and readiness without overriding derived status.", anchor: "packages/plan-mcp/src/index.ts:647", coverage: { phase: "P059", reason: "covered by cross-harness mutation parity regressions" } },
  { id: "mcp.phaseUpdate", kind: "tool", name: "planner-phase-update", description: "Update canonical phase planning fields and parent relinking.", anchor: "packages/plan-mcp/src/index.ts:682", coverage: { phase: "P059", reason: "covered by cross-harness mutation parity regressions" } },
  { id: "mcp.phaseDelete", kind: "tool", name: "planner-phase-delete", description: "Delete phase.", anchor: "packages/plan-mcp/src/index.ts:709", coverage: { phase: "P055", reason: "covered by MCP adapter scenarios (P055)" } },
  { id: "mcp.taskAdd", kind: "tool", name: "planner-task-add", description: "Create task (validates title/phase).", anchor: "packages/plan-mcp/src/index.ts:725" },
  { id: "mcp.taskShow", kind: "tool", name: "planner-task-show", description: "Task detail with canonical Accepted Decisions, resume context, and statusLog before full-read attestation.", anchor: "packages/plan-mcp/src/index.ts:planner-task-show", coverage: { phase: "P059", reason: "covered by MCP Accepted Decision full-read regressions." } },
  { id: "mcp.taskDiscuss", kind: "tool", name: "planner-task-discuss", description: "Persist task discovery.", anchor: "packages/plan-mcp/src/index.ts:801", coverage: { phase: "P055", reason: "covered by MCP adapter scenarios (P055)" } },
  { id: "mcp.taskUpdate", kind: "tool", name: "planner-task-update", description: "Update canonical task context, decisions, checklist, and subtask fields with lifecycle motivation gates.", anchor: "packages/plan-mcp/src/index.ts:829", coverage: { phase: "P059", reason: "covered by cross-harness mutation parity regressions" } },
  { id: "mcp.taskDependencyAdd", kind: "tool", name: "planner-task-dependency-add", description: "Add validated task dependency edges with self, foreign-task, and cycle rejection.", anchor: "packages/plan-mcp/src/index.ts:planner-task-dependency-add", coverage: { phase: "P059", reason: "Covered by dependency graph regressions." } },
  { id: "mcp.taskDependencyDelete", kind: "tool", name: "planner-task-dependency-delete", description: "Remove a confirmed task dependency edge.", anchor: "packages/plan-mcp/src/index.ts:planner-task-dependency-delete", coverage: { phase: "P059", reason: "Covered by dependency graph regressions." } },
  { id: "mcp.taskChecklistToggle", kind: "tool", name: "planner-task-checklist-toggle", description: "Toggle checklist item.", anchor: "packages/plan-mcp/src/index.ts:887" },
  { id: "mcp.taskChecklistAdd", kind: "tool", name: "planner-task-checklist-add", description: "Add checklist item.", anchor: "packages/plan-mcp/src/index.ts:915" },
  { id: "mcp.taskChecklistRemove", kind: "tool", name: "planner-task-checklist-remove", description: "Remove checklist item.", anchor: "packages/plan-mcp/src/index.ts:941" },
  { id: "mcp.taskDelete", kind: "tool", name: "planner-task-delete", description: "Delete task.", anchor: "packages/plan-mcp/src/index.ts:967", coverage: { phase: "P055", reason: "covered by MCP adapter scenarios (P055)" } },
  { id: "mcp.taskStart", kind: "tool", name: "planner-task-start", description: "Start task and deliver bounded canonical phase work-map context with sibling capability ownership before implementation.", anchor: "packages/plan-mcp/src/index.ts:planner-task-start", coverage: { phase: "P059", reason: "Covered by MCP task-start phase work-map regression." } },
  { id: "mcp.taskReopen", kind: "tool", name: "planner-task-reopen", description: "Confirmation-gated atomic task reopening with typed no-op outcomes and retained completion evidence.", anchor: "packages/plan-mcp/src/index.ts:planner-task-reopen", coverage: { phase: "P059", reason: "Covered by MCP reopen regressions." } },
  { id: "mcp.taskComplete", kind: "tool", name: "planner-task-complete", description: "Complete task (sets completedAt; checklist advisory).", anchor: "packages/plan-mcp/src/index.ts:1037" },
  { id: "mcp.taskRecommend", kind: "tool", name: "planner-task-recommend", description: "Return bounded next-work selection plus typed claims from persisted active work, deviations, verified handoffs, and satisfied dependencies; Markdown prose and terminal archives are non-authoritative.", anchor: "packages/plan-mcp/src/index.ts:planner-task-recommend", coverage: { phase: "P059", reason: "Covered by MCP handoff and next-work claim regressions." } },
  { id: "mcp.handoffList", kind: "tool", name: "planner-handoff-list", description: "Pending handoffs.", anchor: "packages/plan-mcp/src/index.ts:1082" },
  { id: "mcp.handoffShow", kind: "tool", name: "planner-handoff-show", description: "Read the active phase handoff or latest terminal archive with discoverable closeout references and a bounded priority-ordered sibling capability map.", anchor: "packages/plan-mcp/src/index.ts:planner-handoff-show", coverage: { phase: "P059", reason: "Covered by MCP terminal archive and phase work-map regressions." } },
  { id: "mcp.handoffWrite", kind: "tool", name: "planner-handoff-write", description: "Require structured title/reason preflight inputs, generate metadata, and persist one scaffold-complete candidate with resumeReady=false pending read-back.", anchor: "packages/plan-mcp/src/index.ts:planner-handoff-write" },
  { id: "mcp.handoffVerify", kind: "tool", name: "planner-handoff-verify", description: "Finalize a shown persisted handoff only after fresh source reconciliation finds no omissions.", anchor: "packages/plan-mcp/src/index.ts:planner-handoff-verify" },
  { id: "mcp.handoffPrepare", kind: "tool", name: "planner-handoff-prepare", description: "Return the exact pre-draft scaffold, structured title/reason inputs, generated-metadata contract, bounded sibling capability map, audits, token, and inline budget.", anchor: "packages/plan-mcp/src/index.ts:planner-handoff-prepare", coverage: { phase: "P059", reason: "Covered by MCP handoff preparation phase work-map regression." } },
  { id: "mcp.handoffClear", kind: "tool", name: "planner-handoff-clear", description: "Clear/archive handoff.", anchor: "packages/plan-mcp/src/index.ts:1149" },
  { id: "mcp.web", kind: "tool", name: "planner-web", description: "Start/stop/status in-process web dashboard with typed reachable address/host/port metadata.", anchor: "packages/plan-mcp/src/index.ts:1160", coverage: { phase: "P059", reason: "Covered by MCP planner-web structured address regression." } },
  { id: "mcp.load", kind: "tool", name: "planner-load", description: "Start web + recap with bounded project/feature/phase/task Accepted Decision agentContext.", anchor: "packages/plan-mcp/src/index.ts:planner-load", coverage: { phase: "P059", reason: "covered by MCP planner-load Accepted Decision context regressions." } },
  { id: "mcp.disable", kind: "tool", name: "planner-disable", description: "MCP no-op disable.", anchor: "packages/plan-mcp/src/index.ts:1209", coverage: { phase: "P055", reason: "covered by MCP adapter scenarios (P055)" } },
];

/**
 * Pi adapter (packages/pi-adapter/src/index.ts).
 * @type {SurfaceEntry[]}
 */
export const piSurfaces = [
  { id: "pi.command", kind: "command", name: "/planner <subcommand>", description: "Hierarchical command: init/show/version/repair/cleanup-orphans/project <discuss|language|guidelines>/idea <list|add|show|update|delete|promote>/feature <add|show|discuss|update|delete|list>/phase <add|show|discuss|update|delete|list>/task <add|show|discuss|update|delete|list|start|complete|checklist <toggle|add|remove>>/handoff <list|show|write|clear|prepare>/bypass/clear-bypass/load/stop|disable/web <status>.", anchor: "packages/pi-adapter/src/index.ts:2424", coverage: { phase: "P056", reason: "covered by Pi adapter scenarios (P056)" } },
  { id: "pi.sessionStart", kind: "hook", name: "session_start", description: "Restore state, autocomplete, planner gating (disabled until /planner load), proactive handoff notice.", anchor: "packages/pi-adapter/src/index.ts:805", coverage: { phase: "P056", reason: "covered by Pi adapter scenarios (P056)" } },
  { id: "pi.sessionBeforeSwitch", kind: "hook", name: "session_before_switch", description: "Write project handoff before switching session.", anchor: "packages/pi-adapter/src/index.ts:896", coverage: { phase: "P056", reason: "covered by Pi adapter scenarios (P056)" } },
  { id: "pi.sessionBeforeCompact", kind: "hook", name: "session_before_compact", description: "Write project handoff before compact.", anchor: "packages/pi-adapter/src/index.ts:905", coverage: { phase: "P056", reason: "covered by Pi adapter scenarios (P056)" } },
  { id: "pi.sessionShutdown", kind: "hook", name: "session_shutdown", description: "Write handoff + stop web server + reset state.", anchor: "packages/pi-adapter/src/index.ts:915", coverage: { phase: "P056", reason: "covered by Pi adapter scenarios (P056)" } },
  { id: "pi.messageEnd", kind: "hook", name: "message_end", description: "Resume summary after load trigger.", anchor: "packages/pi-adapter/src/index.ts:927", coverage: { phase: "P056", reason: "covered by Pi adapter scenarios (P056)" } },
  { id: "pi.toolCall", kind: "hook", name: "tool_call", description: "Task-complete reminder tracking (editedThisTurn).", anchor: "packages/pi-adapter/src/index.ts:959", coverage: { phase: "P056", reason: "covered by Pi adapter scenarios (P056)" } },
  { id: "pi.turnStart", kind: "hook", name: "turn_start", description: "Context block build/injection.", anchor: "packages/pi-adapter/src/index.ts:1014", coverage: { phase: "P056", reason: "covered by Pi adapter scenarios (P056)" } },
  { id: "pi.toolResult", kind: "hook", name: "tool_result", description: "Heal status roots on mutation tool results.", anchor: "packages/pi-adapter/src/index.ts:1021", coverage: { phase: "P056", reason: "covered by Pi adapter scenarios (P056)" } },
  { id: "pi.tool.projectSetLanguage", kind: "tool", name: "project_set_language_preferences", description: "Persist language prefs.", anchor: "packages/pi-adapter/src/index.ts:2456", coverage: { phase: "P056", reason: "covered by Pi adapter scenarios (P056)" } },
  { id: "pi.tool.planInit", kind: "tool", name: "plan_init", description: "Initialize planner.", anchor: "packages/pi-adapter/src/index.ts:2489" },
  { id: "pi.tool.projectUpdate", kind: "tool", name: "project_update", description: "Update project metadata.", anchor: "packages/pi-adapter/src/index.ts:2546" },
  { id: "pi.tool.projectGuidelinesShow", kind: "tool", name: "project_guidelines_show", description: "Read canonical Project Guidelines.", anchor: "packages/pi-adapter/src/index.ts:2846", coverage: { phase: "P056", reason: "covered by Pi adapter integration scenarios in the registered tool suite." } },
  { id: "pi.tool.projectGuidelinesUpdate", kind: "tool", name: "project_guidelines_update", description: "Replace canonical Project Guidelines.", anchor: "packages/pi-adapter/src/index.ts:2873", coverage: { phase: "P056", reason: "covered by Pi adapter integration scenarios in the registered tool suite." } },
  { id: "pi.tool.projectContextMigrate", kind: "tool", name: "project_context_migrate", description: "Preview or apply explicit legacy project-context migration.", anchor: "packages/pi-adapter/src/index.ts:2994", coverage: { phase: "P056", reason: "covered by Pi adapter integration scenarios in the registered tool suite." } },
  { id: "pi.tool.acceptedDecisionCreate", kind: "tool", name: "accepted_decision_create", description: "Create one Accepted Decision on any canonical owner.", anchor: "packages/pi-adapter/src/index.ts:accepted_decision_create", coverage: { phase: "P059", reason: "covered by Pi semantic Accepted Decisions CRUD regressions" } },
  { id: "pi.tool.acceptedDecisionUpdate", kind: "tool", name: "accepted_decision_update", description: "Update one Accepted Decision while preserving planner-owned metadata.", anchor: "packages/pi-adapter/src/index.ts:accepted_decision_update", coverage: { phase: "P059", reason: "covered by Pi semantic Accepted Decisions CRUD regressions" } },
  { id: "pi.tool.acceptedDecisionDelete", kind: "tool", name: "accepted_decision_delete", description: "Delete one Accepted Decision after explicit confirmation.", anchor: "packages/pi-adapter/src/index.ts:accepted_decision_delete", coverage: { phase: "P059", reason: "covered by Pi semantic Accepted Decisions CRUD regressions" } },
  { id: "pi.tool.requirementList", kind: "tool", name: "requirement_list", description: "List statusless product Requirements without attestation, or deliver and attest only target-relevant Requirements when phaseRef is supplied.", anchor: "packages/pi-adapter/src/index.ts:requirement_list", coverage: { phase: "P059", reason: "covered by cross-harness target-scoped requirement-read regressions." } },
  { id: "pi.tool.requirementCreate", kind: "tool", name: "requirement_create", description: "Create a statusless product Requirement; route coding/process rules to Project Guidelines.", anchor: "packages/pi-adapter/src/index.ts:2596" },
  { id: "pi.tool.requirementUpdate", kind: "tool", name: "requirement_update", description: "Update a statusless Requirement outcome/linkage/macro tasks; route coding/process rules to Project Guidelines.", anchor: "packages/pi-adapter/src/index.ts:2628", coverage: { phase: "P056", reason: "covered by Pi adapter scenarios (P056)" } },
  { id: "pi.tool.requirementDelete", kind: "tool", name: "requirement_delete", description: "Delete requirement.", anchor: "packages/pi-adapter/src/index.ts:2656", coverage: { phase: "P056", reason: "covered by Pi adapter scenarios (P056)" } },
  { id: "pi.tool.planGet", kind: "tool", name: "plan_get", description: "Full plan read.", anchor: "packages/pi-adapter/src/index.ts:2677", coverage: { phase: "P056", reason: "covered by Pi adapter scenarios (P056)" } },
  { id: "pi.tool.descriptionFreshness", kind: "tool", name: "description_freshness", description: "Preview exact stale feature/phase refs and explicit reconciliation steps without rewriting parent prose.", anchor: "packages/pi-adapter/src/index.ts:description_freshness", coverage: { phase: "P059", reason: "Covered by Pi hierarchical freshness regression." } },
  { id: "pi.tool.planRender", kind: "tool", name: "plan_render", description: "Regenerate markdown views.", anchor: "packages/pi-adapter/src/index.ts:2693", coverage: { phase: "P056", reason: "covered by Pi adapter scenarios (P056)" } },
  { id: "pi.tool.planRepair", kind: "tool", name: "plan_repair", description: "Repair integrity.", anchor: "packages/pi-adapter/src/index.ts:2706", coverage: { phase: "P056", reason: "covered by Pi adapter scenarios (P056)" } },
  { id: "pi.tool.planCleanupOrphans", kind: "tool", name: "plan_cleanup_orphan_phases", description: "Cleanup orphan phases.", anchor: "packages/pi-adapter/src/index.ts:2730" },
  { id: "pi.tool.planGetHandoff", kind: "tool", name: "plan_get_handoff", description: "DEPRECATED → handoff list.", anchor: "packages/pi-adapter/src/index.ts:2760", coverage: { phase: "P056", reason: "covered by Pi adapter scenarios (P056)" } },
  { id: "pi.tool.planWriteHandoff", kind: "tool", name: "plan_write_handoff", description: "DEPRECATED → handoff write.", anchor: "packages/pi-adapter/src/index.ts:2775", coverage: { phase: "P056", reason: "covered by Pi adapter scenarios (P056)" } },
  { id: "pi.tool.planDeleteHandoff", kind: "tool", name: "plan_delete_handoff", description: "DEPRECATED → handoff clear.", anchor: "packages/pi-adapter/src/index.ts:2818", coverage: { phase: "P056", reason: "covered by Pi adapter scenarios (P056)" } },
  { id: "pi.tool.handoffList", kind: "tool", name: "handoff_list", description: "Pending handoffs.", anchor: "packages/pi-adapter/src/index.ts:2863" },
  { id: "pi.tool.handoffShow", kind: "tool", name: "handoff_show", description: "Read the active phase handoff or latest terminal archive with discoverable closeout references and a bounded priority-ordered sibling capability map.", anchor: "packages/pi-adapter/src/index.ts:handoff_show", coverage: { phase: "P059", reason: "Covered by Pi terminal archive and phase work-map regressions." } },
  { id: "pi.tool.handoffPrepare", kind: "tool", name: "handoff_prepare", description: "Return the exact pre-draft scaffold, structured title/reason inputs, generated-metadata contract, bounded sibling capability map, audits, token, and inline budget.", anchor: "packages/pi-adapter/src/index.ts:handoff_prepare", coverage: { phase: "P059", reason: "Covered by Pi handoff preparation phase work-map regression." } },
  { id: "pi.tool.handoffWrite", kind: "tool", name: "handoff_write", description: "Require structured title/reason preflight inputs, generate metadata, and persist one scaffold-complete candidate with resumeReady=false pending read-back.", anchor: "packages/pi-adapter/src/index.ts:handoff_write" },
  { id: "pi.tool.handoffVerify", kind: "tool", name: "handoff_verify", description: "Finalize a shown persisted handoff only after fresh source reconciliation finds no omissions.", anchor: "packages/pi-adapter/src/index.ts:handoff_verify" },
  { id: "pi.tool.handoffClear", kind: "tool", name: "handoff_clear", description: "Clear phase handoff.", anchor: "packages/pi-adapter/src/index.ts:2942" },
  { id: "pi.tool.planAuthorizeBypass", kind: "tool", name: "plan_authorize_bypass", description: "Guard bypass.", anchor: "packages/pi-adapter/src/index.ts:2957", coverage: { phase: "P056", reason: "covered by Pi adapter scenarios (P056)" } },
  { id: "pi.tool.planClearBypass", kind: "tool", name: "plan_clear_bypass", description: "Clear bypass.", anchor: "packages/pi-adapter/src/index.ts:2973", coverage: { phase: "P056", reason: "covered by Pi adapter scenarios (P056)" } },
  { id: "pi.tool.ideaList", kind: "tool", name: "idea_list", description: "List Ideas Inbox entries.", anchor: "packages/pi-adapter/src/index.ts", coverage: { phase: "P056", reason: "covered by Pi adapter Ideas scenarios." } },
  { id: "pi.tool.ideaShow", kind: "tool", name: "idea_show", description: "Show one Idea.", anchor: "packages/pi-adapter/src/index.ts", coverage: { phase: "P056", reason: "covered by Pi adapter Ideas scenarios." } },
  { id: "pi.tool.ideaCreate", kind: "tool", name: "idea_create", description: "Create an Idea.", anchor: "packages/pi-adapter/src/index.ts", coverage: { phase: "P056", reason: "covered by Pi adapter Ideas scenarios." } },
  { id: "pi.tool.ideaUpdate", kind: "tool", name: "idea_update", description: "Update an Idea.", anchor: "packages/pi-adapter/src/index.ts", coverage: { phase: "P056", reason: "covered by Pi adapter Ideas scenarios." } },
  { id: "pi.tool.ideaDelete", kind: "tool", name: "idea_delete", description: "Delete a confirmed Idea.", anchor: "packages/pi-adapter/src/index.ts", coverage: { phase: "P056", reason: "covered by Pi adapter Ideas scenarios." } },
  { id: "pi.tool.ideaPromotionBegin", kind: "tool", name: "idea_promotion_begin", description: "Load grill-me and propose a promotion without writes.", anchor: "packages/pi-adapter/src/index.ts", coverage: { phase: "P056", reason: "covered by Pi adapter Ideas scenarios." } },
  { id: "pi.tool.ideaPromotionFinalize", kind: "tool", name: "idea_promotion_finalize", description: "Record a confirmed promotion to a validated target.", anchor: "packages/pi-adapter/src/index.ts", coverage: { phase: "P056", reason: "covered by Pi adapter Ideas scenarios." } },
  { id: "pi.tool.featureList", kind: "tool", name: "feature_list", description: "Compact feature list.", anchor: "packages/pi-adapter/src/index.ts:2988", coverage: { phase: "P056", reason: "covered by Pi adapter scenarios (P056)" } },
  { id: "pi.tool.featureGet", kind: "tool", name: "feature_get", description: "Feature detail with canonical Accepted Decisions before full-read attestation.", anchor: "packages/pi-adapter/src/index.ts:feature_get", coverage: { phase: "P059", reason: "covered by Pi Accepted Decision full-read regressions." } },
  { id: "pi.tool.featureCreate", kind: "tool", name: "feature_create", description: "Create feature.", anchor: "packages/pi-adapter/src/index.ts:3030" },
  { id: "pi.tool.featureDiscuss", kind: "tool", name: "feature_discuss", description: "Feature discovery.", anchor: "packages/pi-adapter/src/index.ts:3080", coverage: { phase: "P056", reason: "covered by Pi adapter scenarios (P056)" } },
  { id: "pi.tool.featureUpdate", kind: "tool", name: "feature_update", description: "Update canonical feature context fields; rejects raw Accepted Decisions replacement.", anchor: "packages/pi-adapter/src/index.ts:3118", coverage: { phase: "P059", reason: "covered by cross-harness mutation parity regressions" } },
  { id: "pi.tool.featureDelete", kind: "tool", name: "feature_delete", description: "Delete feature.", anchor: "packages/pi-adapter/src/index.ts:3189", coverage: { phase: "P056", reason: "covered by Pi adapter scenarios (P056)" } },
  { id: "pi.tool.phaseList", kind: "tool", name: "phase_list", description: "Compact phase list.", anchor: "packages/pi-adapter/src/index.ts:3227", coverage: { phase: "P056", reason: "covered by Pi adapter scenarios (P056)" } },
  { id: "pi.tool.phaseGet", kind: "tool", name: "phase_get", description: "Phase detail with canonical Accepted Decisions and linked Requirements before full-read attestation.", anchor: "packages/pi-adapter/src/index.ts:phase_get", coverage: { phase: "P059", reason: "covered by Pi Accepted Decision full-read regressions." } },
  { id: "pi.tool.phaseCreate", kind: "tool", name: "phase_create", description: "Create phase.", anchor: "packages/pi-adapter/src/index.ts:3280" },
  { id: "pi.tool.phaseDiscuss", kind: "tool", name: "phase_discuss", description: "Persist phase discovery and readiness without overriding derived status.", anchor: "packages/pi-adapter/src/index.ts:phase_discuss", coverage: { phase: "P059", reason: "covered by cross-harness mutation parity regressions" } },
  { id: "pi.tool.phaseUpdate", kind: "tool", name: "phase_update", description: "Update canonical phase planning fields and parent relinking.", anchor: "packages/pi-adapter/src/index.ts:3345", coverage: { phase: "P059", reason: "covered by cross-harness mutation parity regressions" } },
  { id: "pi.tool.phaseDelete", kind: "tool", name: "phase_delete", description: "Delete phase.", anchor: "packages/pi-adapter/src/index.ts:3431", coverage: { phase: "P056", reason: "covered by Pi adapter scenarios (P056)" } },
  { id: "pi.tool.taskList", kind: "tool", name: "task_list", description: "Compact task list.", anchor: "packages/pi-adapter/src/index.ts:3469", coverage: { phase: "P056", reason: "covered by Pi adapter scenarios (P056)" } },
  { id: "pi.tool.taskGet", kind: "tool", name: "task_get", description: "Task detail with canonical Accepted Decisions and resume context before full-read attestation.", anchor: "packages/pi-adapter/src/index.ts:task_get", coverage: { phase: "P059", reason: "covered by Pi Accepted Decision full-read regressions." } },
  { id: "pi.tool.taskCreate", kind: "tool", name: "task_create", description: "Create task.", anchor: "packages/pi-adapter/src/index.ts:3527" },
  { id: "pi.tool.taskUpdate", kind: "tool", name: "task_update", description: "Update canonical task context and decisions with lifecycle motivation gates; rejects raw Accepted Decisions replacement.", anchor: "packages/pi-adapter/src/index.ts:3599", coverage: { phase: "P059", reason: "covered by cross-harness mutation parity regressions" } },
  { id: "pi.tool.taskDelete", kind: "tool", name: "task_delete", description: "Delete task.", anchor: "packages/pi-adapter/src/index.ts:3679", coverage: { phase: "P056", reason: "covered by Pi adapter scenarios (P056)" } },
  { id: "pi.tool.taskPause", kind: "tool", name: "task_pause", description: "Pause task with a resume checkpoint.", anchor: "packages/pi-adapter/src/index.ts:3930", coverage: { phase: "P059", reason: "Suspension pause tool (F005/P066); registered in F015 cross-harness inventory, scenario deferred to P059." } },
  { id: "pi.tool.taskSwitch", kind: "tool", name: "task_switch", description: "Switch temporary focus with a return target.", anchor: "packages/pi-adapter/src/index.ts:3975", coverage: { phase: "P059", reason: "Suspension switch tool (F005/P066); registered in F015 cross-harness inventory, scenario deferred to P059." } },
  { id: "pi.tool.taskStart", kind: "tool", name: "task_start", description: "Start task and deliver bounded canonical phase work-map context with sibling capability ownership before implementation.", anchor: "packages/pi-adapter/src/index.ts:task_start", coverage: { phase: "P059", reason: "Covered by Pi task-start phase work-map regression." } },
  { id: "pi.tool.taskReopen", kind: "tool", name: "task_reopen", description: "Confirmation-gated atomic task reopening that retains completion evidence and never pauses another owner.", anchor: "packages/pi-adapter/src/index.ts:task_reopen", coverage: { phase: "P059", reason: "Covered by Pi reopen regressions." } },
  { id: "pi.tool.taskDependencyAdd", kind: "tool", name: "task_dependency_add", description: "Add validated task dependency edges with self, foreign-task, and cycle rejection.", anchor: "packages/pi-adapter/src/index.ts:task_dependency_add", coverage: { phase: "P059", reason: "Covered by dependency graph regressions." } },
  { id: "pi.tool.taskDependencyDelete", kind: "tool", name: "task_dependency_delete", description: "Remove a confirmed task dependency edge.", anchor: "packages/pi-adapter/src/index.ts:task_dependency_delete", coverage: { phase: "P059", reason: "Covered by dependency graph regressions." } },
  { id: "pi.tool.taskComplete", kind: "tool", name: "task_complete", description: "Complete task.", anchor: "packages/pi-adapter/src/index.ts:3741" },
  { id: "pi.tool.taskRecommend", kind: "tool", name: "task_recommend", description: "Return bounded next-work selection plus typed claims from persisted active work, deviations, verified handoffs, and satisfied dependencies; Markdown prose and terminal archives are non-authoritative.", anchor: "packages/pi-adapter/src/index.ts:task_recommend", coverage: { phase: "P059", reason: "Covered by Pi recommendation claim regressions." } },
  { id: "pi.tool.taskChecklistToggle", kind: "tool", name: "task_checklist_toggle", description: "Toggle checklist item.", anchor: "packages/pi-adapter/src/index.ts:3787" },
  { id: "pi.tool.taskChecklistAdd", kind: "tool", name: "task_checklist_add", description: "Add checklist item.", anchor: "packages/pi-adapter/src/index.ts:3820" },
  { id: "pi.tool.taskChecklistRemove", kind: "tool", name: "task_checklist_remove", description: "Remove checklist item.", anchor: "packages/pi-adapter/src/index.ts:3851" },
  { id: "pi.tool.plannerWeb", kind: "tool", name: "planner-web", description: "Start/stop/status dashboard.", anchor: "packages/pi-adapter/src/index.ts:3887" },
  { id: "pi.tool.plannerLoad", kind: "tool", name: "planner-load", description: "Enable planner + web + resume trigger.", anchor: "packages/pi-adapter/src/index.ts:3924" },
  { id: "pi.tool.plannerStop", kind: "tool", name: "planner-stop", description: "Disable planner + stop web.", anchor: "packages/pi-adapter/src/index.ts:3943" },
];

/**
 * Web UI (packages/plan-web-ui).
 * @type {SurfaceEntry[]}
 */
export const uiSurfaces = [
  { id: "ui.apiClient", kind: "module", name: "lib/api.ts", description: "HTTP client used by all loaders/actions (getProject, getFeatures, createFeature, …, listHandoffs, listArchivedHandoffs, setPhaseHandoff, clearPhaseHandoff, repairPlan, reorder).", anchor: "packages/plan-web-ui/src/lib/api.ts", coverage: { phase: "P057", reason: "covered by Web UI harness scenarios (P057)" } },
  { id: "ui.loader.dashboard", kind: "loader", name: "dashboard loader", description: "features + phases + activeTasks.", anchor: "packages/plan-web-ui/src/routes/dashboard/loader.ts" },
  { id: "ui.loader.features", kind: "loader", name: "features loader", description: "features + phases.", anchor: "packages/plan-web-ui/src/routes/features/loader.ts", coverage: { phase: "P057", reason: "covered by Web UI harness scenarios (P057)" } },
  { id: "ui.loader.featureDetail", kind: "loader", name: "feature-detail loader", description: "feature + its phases; 400 when featureId missing.", anchor: "packages/plan-web-ui/src/routes/feature-detail/loader.ts", coverage: { phase: "P057", reason: "covered by Web UI harness scenarios (P057)" } },
  { id: "ui.loader.phaseDetail", kind: "loader", name: "phase-detail loader", description: "current feature + all relink targets + phase + linkedRequirements.", anchor: "packages/plan-web-ui/src/routes/phase-detail/loader.ts", coverage: { phase: "P059", reason: "covered by Web UI mutation parity regressions" } },
  { id: "ui.loader.taskDetail", kind: "loader", name: "task-detail loader", description: "feature + phase + task.", anchor: "packages/plan-web-ui/src/routes/task-detail/loader.ts", coverage: { phase: "P057", reason: "covered by Web UI harness scenarios (P057)" } },
  { id: "ui.action.taskReopen", kind: "action", name: "task-reopen action", description: "Confirmation-gated Web UI action for semantic task reopening.", anchor: "packages/plan-web-ui/src/routes/task-reopen.action.ts", coverage: { phase: "P059", reason: "Covered by Web UI reopen regression." } },
  { id: "ui.loader.requirements", kind: "loader", name: "requirements loader", description: "requirements + phases.", anchor: "packages/plan-web-ui/src/routes/requirements/loader.ts", coverage: { phase: "P057", reason: "covered by Web UI harness scenarios (P057)" } },
  { id: "ui.action.featureCreate", kind: "action", name: "feature-create action", description: "POST createFeature from FormData → redirect /features.", anchor: "packages/plan-web-ui/src/routes/feature-create.action.ts" },
  { id: "ui.action.featureEdit", kind: "action", name: "feature-edit action", description: "PUT canonical feature context including descriptionRef without direct derived-status mutation.", anchor: "packages/plan-web-ui/src/routes/feature-edit.action.ts", coverage: { phase: "P059", reason: "covered by Web UI mutation parity regressions" } },
  { id: "ui.action.featureDelete", kind: "action", name: "feature-delete action", description: "DELETE feature.", anchor: "packages/plan-web-ui/src/routes/feature-delete.action.ts", coverage: { phase: "P057", reason: "covered by Web UI harness scenarios (P057)" } },
  { id: "ui.action.featureStatus", kind: "action", name: "feature-status action", description: "Legacy direct feature-status request; server rejects derived-status changes.", anchor: "packages/plan-web-ui/src/routes/feature-status.action.ts", coverage: { phase: "P057", reason: "covered by Web UI harness scenarios (P057)" } },
  { id: "ui.action.phaseCreate", kind: "action", name: "phase-create action", description: "POST createPhase → redirect feature detail.", anchor: "packages/plan-web-ui/src/routes/phase-create.action.ts" },
  { id: "ui.action.phaseEdit", kind: "action", name: "phase-edit action", description: "PUT canonical planning fields and parent relinking without direct derived-status mutation.", anchor: "packages/plan-web-ui/src/routes/phase-edit.action.ts", coverage: { phase: "P059", reason: "covered by Web UI mutation parity regressions" } },
  { id: "ui.action.phaseDelete", kind: "action", name: "phase-delete action", description: "DELETE phase.", anchor: "packages/plan-web-ui/src/routes/phase-delete.action.ts", coverage: { phase: "P057", reason: "covered by Web UI harness scenarios (P057)" } },
  { id: "ui.action.phaseStatus", kind: "action", name: "phase-status action", description: "Legacy direct phase-status request; server rejects derived-status changes.", anchor: "packages/plan-web-ui/src/routes/phase-status.action.ts", coverage: { phase: "P057", reason: "covered by Web UI harness scenarios (P057)" } },
  { id: "ui.action.taskCreate", kind: "action", name: "task-create action", description: "POST createTask with checklist support.", anchor: "packages/plan-web-ui/src/routes/task-create.action.ts" },
  { id: "ui.action.taskEdit", kind: "action", name: "task-edit action", description: "PUT task descriptionRef, notes, decisions, motivation, checklist, and editable execution fields.", anchor: "packages/plan-web-ui/src/routes/task-edit.action.ts", coverage: { phase: "P059", reason: "covered by Web UI mutation parity regressions" } },
  { id: "ui.action.taskDelete", kind: "action", name: "task-delete action", description: "DELETE task.", anchor: "packages/plan-web-ui/src/routes/task-delete.action.ts", coverage: { phase: "P057", reason: "covered by Web UI harness scenarios (P057)" } },
  { id: "ui.action.taskStatus", kind: "action", name: "task-status action", description: "PUT task status.", anchor: "packages/plan-web-ui/src/routes/task-status.action.ts" },
  { id: "ui.action.taskChecklistToggle", kind: "action", name: "task-checklist-toggle action", description: "Toggle checklist item.", anchor: "packages/plan-web-ui/src/routes/task-checklist-toggle.action.ts", coverage: { phase: "P057", reason: "covered by Web UI harness scenarios (P057)" } },
  { id: "ui.action.requirementCreate", kind: "action", name: "requirement-create action", description: "POST a statusless product Requirement with linkedPhaseIds and Project Guidelines separation guidance.", anchor: "packages/plan-web-ui/src/routes/requirement-create.action.ts" },
  { id: "ui.action.requirementEdit", kind: "action", name: "requirement-edit action", description: "PUT updateRequirement.", anchor: "packages/plan-web-ui/src/routes/requirement-edit.action.ts", coverage: { phase: "P057", reason: "covered by Web UI harness scenarios (P057)" } },
  { id: "ui.action.requirementDelete", kind: "action", name: "requirement-delete action", description: "DELETE requirement.", anchor: "packages/plan-web-ui/src/routes/requirement-delete.action.ts", coverage: { phase: "P057", reason: "covered by Web UI harness scenarios (P057)" } },
  { id: "ui.action.projectEdit", kind: "action", name: "project-edit action", description: "PUT updateProject.", anchor: "packages/plan-web-ui/src/routes/project-edit.action.ts", coverage: { phase: "P057", reason: "covered by Web UI harness scenarios (P057)" } },
  { id: "ui.action.acceptedDecision", kind: "action", name: "accepted-decision action", description: "Create, update, or confirmed-delete one Accepted Decision through semantic API routes.", anchor: "packages/plan-web-ui/src/routes/accepted-decision.action.ts", coverage: { phase: "P059", reason: "covered by Web UI Accepted Decisions management regressions" } },
  { id: "ui.component.acceptedDecisions", kind: "component", name: "AcceptedDecisionsList", description: "Display and manage project, feature, phase, and task Accepted Decisions.", anchor: "packages/plan-web-ui/src/components/ui/accepted-decisions-list.tsx", coverage: { phase: "P059", reason: "covered by Web UI Accepted Decisions management regressions" } },
  { id: "ui.component.descriptionFreshness", kind: "component", name: "DescriptionFreshnessNotice", description: "Show relevant stale-parent reconciliation steps on feature, phase, and task detail surfaces without silently editing parent prose.", anchor: "packages/plan-web-ui/src/components/ui/description-freshness-notice.tsx", coverage: { phase: "P059", reason: "Covered by Web UI description-freshness component regression." } },
  { id: "ui.route.handoff", kind: "route", name: "route /handoff", description: "Handoff list + show with preflight metadata guidance.", anchor: "packages/plan-web-ui/src/routes/handoff.route.tsx", coverage: { phase: "P058", reason: "covered by Playwright handoff e2e scenarios (P058)" } },
  { id: "ui.route.handoffArchive", kind: "route", name: "route /handoff/archive", description: "Archived handoffs view.", anchor: "packages/plan-web-ui/src/routes/handoff-archive.route.tsx" },
  { id: "ui.component.formattedDocLinks", kind: "component", name: "FormattedText doc links", description: "Render .planner/docs/*.md references as new-tab viewer links.", anchor: "packages/plan-web-ui/src/components/ui/formatted-text.tsx", coverage: { phase: "P059", reason: "Covered by Web UI doc-link unit regression." } },
  { id: "ui.route.docViewer", kind: "route", name: "route /docs/view", description: "Path-safe Markdown viewer with dependency-free textarea editor and confirmed save.", anchor: "packages/plan-web-ui/src/routes/doc-viewer.route.tsx", coverage: { phase: "P059", reason: "Covered by responsive Playwright doc-viewer scenario." } },
  { id: "ui.component.workTree", kind: "component", name: "dashboard work-tree", description: "Feature/phase/task tree with status badges.", anchor: "packages/plan-web-ui/src/components/dashboard/work-tree.tsx" },
  { id: "ui.component.statCards", kind: "component", name: "dashboard stat-cards", description: "Progress stat cards.", anchor: "packages/plan-web-ui/src/components/dashboard/stat-cards.tsx" },
  { id: "ui.component.sortable", kind: "component", name: "dashboard sortable", description: "Drag-and-drop reorder (dnd-kit).", anchor: "packages/plan-web-ui/src/components/dashboard/sortable.tsx", coverage: { phase: "P058", reason: "covered by Playwright dashboard e2e scenarios (P058)" } },
  { id: "ui.component.statusStepper", kind: "component", name: "status-card-stepper", description: "Task/phase status stepper.", anchor: "packages/plan-web-ui/src/components/ui/status-card-stepper.tsx" },
  { id: "ui.component.statusHistory", kind: "component", name: "status-history-accordion", description: "StatusLog accordion.", anchor: "packages/plan-web-ui/src/components/ui/status-history-accordion.tsx", coverage: { phase: "P057", reason: "covered by Web UI harness scenarios (P057)" } },
  { id: "ui.component.linkedPhaseSelector", kind: "component", name: "linked-phase-selector", description: "Requirements → phases multi-select.", anchor: "packages/plan-web-ui/src/components/requirements/linked-phase-selector.tsx" },
  { id: "ui.component.badges", kind: "component", name: "badges", description: "Entity ref badges (F/P/T composite).", anchor: "packages/plan-web-ui/src/components/ui/badges.tsx", coverage: { phase: "P057", reason: "covered by Web UI harness scenarios (P057)" } },
  { id: "ui.lib.taskSearch", kind: "lib", name: "lib/task-search.ts", description: "Client-side task search/filter.", anchor: "packages/plan-web-ui/src/lib/task-search.ts", coverage: { phase: "P057", reason: "covered by Web UI harness scenarios (P057)" } },
  { id: "ui.lib.dashboardTree", kind: "lib", name: "lib/dashboard-tree.ts", description: "Tree building from features/phases/tasks.", anchor: "packages/plan-web-ui/src/lib/dashboard-tree.ts", coverage: { phase: "P058", reason: "covered by Playwright dashboard e2e scenarios (P058)" } },
  { id: "ui.lib.liveSync", kind: "lib", name: "app/live-sync.tsx", description: "WebSocket live sync hook.", anchor: "packages/plan-web-ui/src/app/live-sync.tsx", coverage: { phase: "P058", reason: "covered by Playwright live-sync e2e scenarios (P058)" } },
];

/** All surfaces grouped by harness. */
export const surfacesByHarness = {
  core: coreSurfaces,
  api: apiSurfaces,
  mcp: mcpSurfaces,
  pi: piSurfaces,
  ui: uiSurfaces,
};

/** Flat lookup: id → entry. */
export const surfaceById = new Map(
  [...coreSurfaces, ...apiSurfaces, ...mcpSurfaces, ...piSurfaces, ...uiSurfaces].map((entry) => [entry.id, entry]),
);

export function surfaceCount() {
  return surfaceById.size;
}
