/**
 * T228 (P053/F015) — Project and feature creation validation.
 *
 * Core-level coverage (real PlanStore + real filesystem, no mocks):
 *  - project init: full deterministic tree, counters seeded to 1, double-init
 *    rejection, empty-name rejection with no partial project.json
 *  - project update/persist: updateProject + saveProject round-trips through a
 *    fresh PlanStore; invalid updates reject WITHOUT mutating project.json;
 *    global sequence counters persist and reject non-positive values
 *  - feature create: explicit id/shortId/priority stored verbatim; missing and
 *    empty names rejected; whitespace-only names accepted (min(1) counts chars,
 *    no trim at core — API-layer concern); long names accepted (no max at core);
 *    malformed fields rejected (negative number/priority, bad shortId, empty
 *    phaseId, missing/invalid timestamps); duplicate names allowed (no
 *    uniqueness at core); non-UUID ids/phaseIds stored verbatim (UUID gate
 *    lives at adapter/API)
 *  - invalid saves do NOT write files (parse happens before atomic write)
 *  - feature update/delete via updateFeatures: rename+workDone persists; delete
 *    removes the feature FILE; phase files remain on disk → orphan phases
 *    reported (delete at core has no cascade — pin)
 *  - generated markdown: views are NOT auto-regenerated by plain feature/
 *    project writes — writeGenerated() must be called explicitly (pinned);
 *    after regeneration PLAN.md reflects the canonical JSON
 *  - stable refs: formatFeatureRef padding, explicit shortId survival
 *
 * Enforcement notes (recorded for later phases):
 *  - whitespace-only names/descriptions and duplicate names pass the core
 *    schema; stricter uniqueness/trim gates (if desired) live at the API layer
 *    (serve.ts, P054).
 *  - feature number assignment at creation lives in the API layer (POST
 *    /features); the core counter (project.nextFeatureNumber) is preserved here
 *    as the monotonic-sequence contract.
 */

import { test, after } from "node:test";
import assert from "node:assert/strict";
import { readFile, readdir } from "node:fs/promises";
import { join } from "node:path";
import {
  PlanStore,
  FeatureSchema,
  ProjectSchema,
  createFeatureId,
  createShortId,
  formatFeatureRef,
} from "../dist/index.js";
import {
  createPlannerFixture,
  readPlanSnapshot,
  cleanupFixtures,
  fixturePaths,
  BASE_TIME,
} from "../../../test/helpers/fixtures.mjs";

after(async () => {
  await cleanupFixtures();
});

const NOW = BASE_TIME;
const TS = { createdAt: NOW, updatedAt: NOW };

/** Raw (unparsed) feature — saveFeature/FeatureSchema does the validation. */
function makeFeature(overrides = {}) {
  return {
    id: createFeatureId(),
    number: 1,
    shortId: createShortId(new Set(), "feature"),
    priority: 10,
    name: "Auth API",
    description: "Authentication API.",
    phaseIds: [],
    ...TS,
    ...overrides,
  };
}

async function planMd(planRoot) {
  return readFile(join(planRoot, ".local", "generated", "PLAN.md"), "utf-8");
}

function reopen(planRoot) {
  const store = new PlanStore(planRoot);
  store.enableAutoSync(true);
  return store;
}

// ────────────────────────────────────────────────────────────────────────────
// Project init
// ────────────────────────────────────────────────────────────────────────────

test("project init: creates the full deterministic tree and seeds counters to 1", async () => {
  const { planRoot, store } = await createPlannerFixture({ name: "init-tree", seed: "empty" });
  const paths = fixturePaths(planRoot);
  const snapshot = await readPlanSnapshot(planRoot);
  assert.equal(snapshot.manifest.projectName, "init-tree");
  assert.equal(snapshot.manifest.schemaVersion, 1);
  assert.deepEqual(snapshot.requirements, { requirements: [] });
  assert.deepEqual(snapshot.features, []);
  assert.deepEqual(snapshot.phases, []);
  assert.equal(snapshot.project.name, "init-tree");
  assert.equal(snapshot.project.nextFeatureNumber, 1);
  assert.equal(snapshot.project.nextPhaseNumber, 1);
  assert.equal(snapshot.project.nextTaskNumber, 1);
  assert.deepEqual(snapshot.project.scope, []);
  assert.deepEqual(snapshot.project.technologies, []);
  // generated views + resume are written at init
  const md = await planMd(planRoot);
  assert.match(md, /Project Plan/);
  const resume = JSON.parse(await readFile(paths.resume, "utf-8"));
  assert.equal(resume.currentPhaseId, "");
  assert.ok(Array.isArray(resume.nextSteps));
  void store;
});

test("project init: rejects when .planner/ already exists", async () => {
  const { planRoot } = await createPlannerFixture({ name: "init-twice", seed: "empty" });
  // same store
  await assert.rejects(() => new PlanStore(planRoot).init("second"), /already exists/);
  // fresh store over the same root
  await assert.rejects(() => reopen(planRoot).init("second"), /already exists/);
});

test("project init: empty name rejects and leaves no project.json; whitespace name is accepted", async () => {
  const { createTempRoot } = await import("../../../test/helpers/fixtures.mjs");
  const { readFile: rf } = await import("node:fs/promises");
  // empty name: init fails inside saveProject, so project.json must NOT exist.
  // (The dir tree IS created before saveProject — a later init on the same
  // root is rejected as "already exists", pinned below.)
  const bare1 = await createTempRoot("init-blank-");
  const fresh1 = new PlanStore(join(bare1, ".planner"));
  await assert.rejects(() => fresh1.init(""), /name/i);
  await assert.rejects(rf(join(bare1, ".planner", "project.json")), { code: "ENOENT" });
  await assert.rejects(() => fresh1.init("second"), /already exists/, "failed init still created the dir tree");
  // min(1) counts characters: a whitespace-only name passes the core schema
  const bare2 = await createTempRoot("init-ws-");
  const fresh2 = new PlanStore(join(bare2, ".planner"));
  await fresh2.init("   ");
  assert.equal((await fresh2.loadProject()).name, "   ");
});

// ────────────────────────────────────────────────────────────────────────────
// Project update / persistence
// ────────────────────────────────────────────────────────────────────────────

test("project update: rich update persists through a fresh PlanStore", async () => {
  const { planRoot, store } = await createPlannerFixture({ name: "proj-update", seed: "empty" });
  await store.updateProject((p) => ({
    ...p,
    goal: "Ship a harness-agnostic planner",
    description: "Longer project description.",
    webPort: 4173,
    scope: ["core", "adapters"],
    outOfScope: ["mobile"],
    technologies: ["TypeScript", "Hono"],
    tools: ["pnpm", "vitest"],
    globalRules: ["One task at a time"],
    decisions: ["Real fixtures, no mocks"],
    contentLanguage: "it",
    chatLanguage: "it",
  }));
  const reopened = reopen(planRoot);
  const project = await reopened.loadProject();
  assert.equal(project.goal, "Ship a harness-agnostic planner");
  assert.equal(project.webPort, 4173);
  assert.deepEqual(project.scope, ["core", "adapters"]);
  assert.deepEqual(project.technologies, ["TypeScript", "Hono"]);
  assert.deepEqual(project.globalRules, ["One task at a time"]);
  assert.equal(project.contentLanguage, "it");
  assert.equal(project.nextFeatureNumber, 1, "counters untouched by plain updates");
});

test("project update: invalid update rejects and does NOT mutate project.json", async () => {
  const { planRoot, store } = await createPlannerFixture({ name: "proj-invalid", seed: "empty" });
  const before = await readFile(join(planRoot, "project.json"), "utf-8");
  await assert.rejects(() => store.updateProject((p) => ({ ...p, name: "" })), /name/i);
  await assert.rejects(() => store.updateProject((p) => ({ ...p, webPort: 70000 })), /webPort/);
  await assert.rejects(() => store.updateProject((p) => ({ ...p, scope: [""] })), /scope/);
  const after = await readFile(join(planRoot, "project.json"), "utf-8");
  assert.equal(after, before, "project.json byte-identical after rejected updates");
});

test("project saveProject: full explicit project round-trips deep-equal", async () => {
  const { planRoot, store } = await createPlannerFixture({ name: "proj-save", seed: "empty" });
  const explicit = ProjectSchema.parse({
    name: "Round-trip project",
    goal: "Goal",
    description: "Desc",
    webPort: 8080,
    scope: ["a", "b"],
    outOfScope: ["c"],
    decisions: ["d1"],
    globalRules: ["g1"],
    technologies: ["t1"],
    tools: ["tool1"],
    contentLanguage: "en",
    chatLanguage: "en",
    workflowRules: { beforePhaseStart: [], beforeTaskStart: [], afterPhaseComplete: [] },
    acceptedDecisions: [],
    nextFeatureNumber: 7,
    nextPhaseNumber: 3,
    nextTaskNumber: 12,
    workDeviations: [],
  });
  await store.saveProject(explicit);
  const reopened = reopen(planRoot);
  const loaded = await reopened.loadProject();
  assert.equal(loaded.name, "Round-trip project");
  assert.equal(loaded.webPort, 8080);
  assert.equal(loaded.nextFeatureNumber, 7);
  assert.equal(loaded.nextTaskNumber, 12);
  assert.deepEqual(loaded.workDeviations, []);
});

test("project counters: non-positive values are rejected without mutation", async () => {
  const { planRoot, store } = await createPlannerFixture({ name: "proj-counters", seed: "empty" });
  const before = await readFile(join(planRoot, "project.json"), "utf-8");
  for (const field of ["nextFeatureNumber", "nextPhaseNumber", "nextTaskNumber"]) {
    await assert.rejects(() => store.updateProject((p) => ({ ...p, [field]: 0 })), new RegExp(field));
    await assert.rejects(() => store.updateProject((p) => ({ ...p, [field]: -3 })), new RegExp(field));
  }
  const after = await readFile(join(planRoot, "project.json"), "utf-8");
  assert.equal(after, before);
});

// ────────────────────────────────────────────────────────────────────────────
// Feature create
// ────────────────────────────────────────────────────────────────────────────

test("feature create: explicit id/shortId/priority stored verbatim and stable", async () => {
  const { planRoot, store } = await createPlannerFixture({ name: "feat-explicit", seed: "empty" });
  const shortId = createShortId(new Set(), "feature-explicit");
  const id = createFeatureId();
  await store.saveFeature(makeFeature({ id, shortId, priority: 42, number: 3, name: "Explicit feature" }));
  const reopened = reopen(planRoot);
  const loaded = (await reopened.loadFeatures()).features.find((f) => f.id === id);
  assert.equal(loaded.id, id, "explicit id preserved");
  assert.equal(loaded.shortId, shortId, "explicit shortId preserved");
  assert.equal(loaded.priority, 42, "explicit priority preserved");
  assert.equal(loaded.number, 3);
  assert.equal(formatFeatureRef(loaded.number), "F003", "composite ref is stable");
  assert.match(loaded.shortId, /^[A-Z2-9]{5}$/);
  // per-feature file exists at features/<id>.json
  const raw = JSON.parse(await readFile(join(planRoot, "features", `${id}.json`), "utf-8"));
  assert.equal(raw.name, "Explicit feature");
  // generated markdown reflects creation ONLY after an explicit writeGenerated
  const beforeRegen = await planMd(planRoot);
  assert.ok(!beforeRegen.includes("Explicit feature"), "plain saveFeature does not auto-regenerate views");
  await store.writeGenerated();
  const md = await planMd(planRoot);
  assert.match(md, /F003 — Explicit feature/);
});

test("feature create: missing and empty names are rejected without writing a file", async () => {
  const { planRoot, store } = await createPlannerFixture({ name: "feat-name", seed: "empty" });
  await assert.rejects(() => store.saveFeature(makeFeature({ name: undefined })), /name/i);
  await assert.rejects(() => store.saveFeature(makeFeature({ name: "" })), /name/i);
  const files = await readdir(join(planRoot, "features"));
  assert.deepEqual(files, [], "no feature file written for rejected saves");
  const snapshot = await readPlanSnapshot(planRoot);
  assert.deepEqual(snapshot.features, []);
});

test("feature create: whitespace-only names and very long names are accepted (no trim/max at core)", async () => {
  const { planRoot, store } = await createPlannerFixture({ name: "feat-len", seed: "empty" });
  const longName = "F".repeat(2000);
  const id1 = createFeatureId();
  const id2 = createFeatureId();
  await store.saveFeature(makeFeature({ id: id1, name: "   " }));
  await store.saveFeature(makeFeature({ id: id2, number: 2, name: longName }));
  const reopened = reopen(planRoot);
  const loaded = await reopened.loadFeatures();
  assert.equal(loaded.features.find((f) => f.id === id1).name, "   ", "whitespace name stored verbatim");
  assert.equal(loaded.features.find((f) => f.id === id2).name.length, 2000, "no max length at core");
});

test("feature create: malformed fields are rejected by the schema", async () => {
  const { planRoot, store } = await createPlannerFixture({ name: "feat-malformed", seed: "empty" });
  await assert.rejects(() => store.saveFeature(makeFeature({ number: -1 })), /number/);
  await assert.rejects(() => store.saveFeature(makeFeature({ priority: -5 })), /priority/);
  for (const shortId of ["abcde", "AB1DE", "ABCDEF", "A B C", "ABCD*"]) {
    await assert.rejects(() => store.saveFeature(makeFeature({ shortId })), /shortId/);
  }
  await assert.rejects(() => store.saveFeature(makeFeature({ phaseIds: [""] })), /phaseIds/);
  // empty shortId is the documented default
  await store.saveFeature(makeFeature({ shortId: "" }));
  // non-UUID phaseIds are accepted on WRITE (min(1) string; UUID gates are
  // API-level) but pruned on LOAD by normalizeStructureSnapshot (self-healing
  // reads, same contract pinned in T230 for dangling feature→phase refs)
  const id = createFeatureId();
  await store.saveFeature(makeFeature({ id, phaseIds: ["not-a-uuid"] }));
  const raw = JSON.parse(await readFile(join(planRoot, "features", `${id}.json`), "utf-8"));
  assert.deepEqual(raw.phaseIds, ["not-a-uuid"], "stored verbatim on write");
  assert.deepEqual(
    (await store.loadFeatures()).features.find((f) => f.id === id).phaseIds,
    [],
    "unresolvable phaseIds pruned on load",
  );
});

test("feature create: missing/invalid timestamps are rejected", async () => {
  const { store } = await createPlannerFixture({ name: "feat-ts", seed: "empty" });
  const noCreated = makeFeature();
  delete noCreated.createdAt;
  await assert.rejects(() => store.saveFeature(noCreated), /createdAt/);
  const noUpdated = makeFeature();
  delete noUpdated.updatedAt;
  await assert.rejects(() => store.saveFeature(noUpdated), /updatedAt/);
  await assert.rejects(() => store.saveFeature(makeFeature({ createdAt: "2026-01-01" })), /createdAt/);
  await assert.rejects(() => store.saveFeature(makeFeature({ updatedAt: "not-a-date" })), /updatedAt/);
});

test("feature create: duplicate names allowed at core; non-UUID ids stored verbatim", async () => {
  const { planRoot, store } = await createPlannerFixture({ name: "feat-dup", seed: "empty" });
  const id1 = createFeatureId();
  const id2 = createFeatureId();
  await store.saveFeature(makeFeature({ id: id1, number: 1, name: "Same name" }));
  await store.saveFeature(makeFeature({ id: id2, number: 2, name: "Same name" }));
  const reopened = reopen(planRoot);
  const loaded = await reopened.loadFeatures();
  assert.equal(loaded.features.length, 2, "duplicate names both persist (no uniqueness at core)");
  assert.ok(loaded.features.every((f) => f.name === "Same name"));
  assert.notEqual(loaded.features[0].id, loaded.features[1].id);

  // non-UUID id: the core schema is a plain string — enforcement lives at API
  const customId = "custom-feature-1";
  await store.saveFeature(makeFeature({ id: customId, number: 3, name: "Custom id" }));
  const loadedCustom = (await reopen(planRoot).loadFeatures()).features.find((f) => f.id === customId);
  assert.equal(loadedCustom?.name, "Custom id", "non-UUID id stored verbatim at core");
});

// ────────────────────────────────────────────────────────────────────────────
// Feature update / delete
// ────────────────────────────────────────────────────────────────────────────

test("feature update: rename + workDone persist; views update after explicit writeGenerated", async () => {
  const { planRoot, store } = await createPlannerFixture({ name: "feat-update", seed: "minimal" });
  const feature = (await store.loadFeatures()).features[0];
  await store.updateFeatures((doc) => {
    const f = doc.features.find((x) => x.id === feature.id);
    f.name = "Auth API v2";
    f.description = "Renamed during update.";
    f.workDone = "Schema + CRUD";
    f.workRemaining = "Tests";
    return doc;
  });
  const reopened = reopen(planRoot);
  const loaded = (await reopened.loadFeatures()).features.find((f) => f.id === feature.id);
  assert.equal(loaded.name, "Auth API v2");
  assert.equal(loaded.workDone, "Schema + CRUD");
  assert.equal(loaded.workRemaining, "Tests");
  const beforeRegen = await planMd(planRoot);
  assert.ok(!beforeRegen.includes("Auth API v2"), "plain updateFeatures does not auto-regenerate views");
  await store.writeGenerated();
  const md = await planMd(planRoot);
  assert.match(md, /F001 — Auth API v2/);
});

test("feature delete: removes the file and regenerates views; phases become orphans (no cascade)", async () => {
  const { planRoot, store } = await createPlannerFixture({ name: "feat-delete", seed: "minimal" });
  const feature = (await store.loadFeatures()).features[0];
  const phase = (await store.loadAllPhases())[0];
  await store.writeGenerated();
  const beforeMd = await planMd(planRoot);
  assert.match(beforeMd, /F001 — Auth API/, "PLAN.md lists the feature before deletion");

  await store.updateFeatures((doc) => {
    doc.features = doc.features.filter((f) => f.id !== feature.id);
    return doc;
  });
  const files = await readdir(join(planRoot, "features"));
  assert.ok(!files.includes(`${feature.id}.json`), "feature file removed");
  // views still stale until explicitly regenerated
  const staleMd = await planMd(planRoot);
  assert.ok(staleMd.includes("F001 — Auth API"), "views are not auto-regenerated by delete either");
  await store.writeGenerated();
  const md = await planMd(planRoot);
  assert.ok(!md.includes("F001 — Auth API"), "PLAN.md no longer lists the deleted feature after regen");
  // core delete has NO cascade: the phase file stays on disk and is reported as orphan
  const phaseFiles = await readdir(join(planRoot, "phases"));
  assert.equal(phaseFiles.length, 1, "phase file preserved (no cascade at core)");
  const orphans = await store.listOrphanPhases();
  assert.equal(orphans.length, 1);
  assert.equal(orphans[0].phaseId, phase.id, "orphan points at the unlinked phase");
  assert.ok((await store.loadAllPhases()).some((p) => p.id === phase.id), "phase still loadable");
});

test("feature update: invalid document rejects and leaves files unchanged", async () => {
  const { planRoot, store } = await createPlannerFixture({ name: "feat-invalid-update", seed: "minimal" });
  const before = await readdir(join(planRoot, "features"));
  const beforeMd = await planMd(planRoot);
  await assert.rejects(
    () => store.updateFeatures((doc) => {
      doc.features[0].name = "";
      return doc;
    }),
    /name/,
  );
  const after = await readdir(join(planRoot, "features"));
  assert.deepEqual(after, before, "no feature files changed");
  assert.equal(await planMd(planRoot), beforeMd, "generated view unchanged");
});
